-- Generated by Ora2Pg, the Oracle database Schema converter, version 19.1
-- Copyright 2000-2018 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=localhost;sid=orcl;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE SCHEMA pbs_datastore;
--ALTER SCHEMA pbs_datastore OWNER TO pbs_datastore;

SET search_path = pbs_datastore;

CREATE TABLE my_stats_table (
	statid varchar(30),
	type char(1),
	version bigint,
	flags bigint,
	c1 varchar(30),
	c2 varchar(30),
	c3 varchar(30),
	c4 varchar(30),
	c5 varchar(30),
	n1 bigint,
	n2 bigint,
	n3 bigint,
	n4 bigint,
	n5 bigint,
	n6 bigint,
	n7 bigint,
	n8 bigint,
	n9 bigint,
	n10 bigint,
	n11 bigint,
	n12 bigint,
	d1 timestamp,
	r1 bytea,
	r2 bytea,
	ch1 varchar(1000),
	cl1 text
) ;
CREATE INDEX idx_my_stats_table ON my_stats_table (statid, type, c5, c1, c2, c3, c4, version);

CREATE TABLE pbs_bndr_linked_det (
	xid integer NOT NULL,
	pbs_clm_txn_xid integer,
	linked_ucr varchar(17),
	linked_tr varchar(17),
	created_date_time timestamp NOT NULL,
	created_user varchar(32) NOT NULL,
	last_updated_date_time timestamp,
	last_updated_user varchar(32)
) ;
CREATE INDEX idx_pbs_bndr_lin_pbs_clm01 ON pbs_bndr_linked_det (pbs_clm_txn_xid);
ALTER TABLE pbs_bndr_linked_det ADD PRIMARY KEY (xid);

CREATE TABLE pbs_bndr_linked_det_hst (
	xid integer NOT NULL,
	pbs_clm_txn_xid integer,
	linked_ucr varchar(17),
	linked_tr varchar(17),
	created_date_time timestamp NOT NULL,
	created_user varchar(32) NOT NULL,
	last_updated_date_time timestamp,
	last_updated_user varchar(32),
	current_row_xid integer,
	history_reason varchar(50),
	history_date_time timestamp
) ;
ALTER TABLE pbs_bndr_linked_det_hst ADD PRIMARY KEY (xid);

CREATE TABLE pbs_claim (
	xid integer NOT NULL,
	ucr varchar(64) NOT NULL,
	ins_contract_xid integer NOT NULL,
	clob_xid integer,
	current_status varchar(32) NOT NULL,
	current_status_datetime timestamp NOT NULL,
	created_date_time timestamp NOT NULL,
	created_user varchar(32) NOT NULL,
	last_updated_date_time timestamp NOT NULL,
	last_updated_user varchar(32) NOT NULL,
	broker_code varchar(16),
	bind_auth_ind varchar(1)
) ;
CREATE INDEX idx_clm_edc ON pbs_claim (clob_xid);
CREATE INDEX idx_clm_ict ON pbs_claim (ins_contract_xid);
ALTER TABLE pbs_claim ADD PRIMARY KEY (xid);
ALTER TABLE pbs_claim ADD UNIQUE (ucr);

CREATE TABLE pbs_claim_hst (
	xid integer NOT NULL,
	ucr varchar(64) NOT NULL,
	ins_contract_xid integer NOT NULL,
	clob_xid integer,
	current_status varchar(32) NOT NULL,
	current_status_datetime timestamp NOT NULL,
	created_date_time timestamp NOT NULL,
	created_user varchar(32) NOT NULL,
	last_updated_date_time timestamp NOT NULL,
	last_updated_user varchar(32) NOT NULL,
	current_row_xid integer,
	history_date_time timestamp,
	history_reason varchar(50),
	broker_code varchar(16),
	bind_auth_ind varchar(1)
) ;
ALTER TABLE pbs_claim_hst ADD PRIMARY KEY (xid);

CREATE TABLE pbs_clm_txn (
	xid integer NOT NULL,
	claim_xid integer NOT NULL,
	current_status varchar(16) NOT NULL,
	current_status_datetime timestamp NOT NULL,
	created_date_time timestamp NOT NULL,
	created_user varchar(32) NOT NULL,
	last_updated_date_time timestamp NOT NULL,
	last_updated_user varchar(32) NOT NULL,
	effective_date_time timestamp,
	clob_xid integer,
	transaction_ref varchar(32) NOT NULL,
	bnd_class varchar(2),
	bnd_sub_class varchar(4),
	bdx_ucr varchar(17),
	bdx_tr varchar(17)
) ;

CREATE TABLE pbs_clm_txn_car_lin (
	xid integer NOT NULL,
	claim_xid integer NOT NULL,
	utr varchar(32),
	cm_submn_xid integer,
	ta_submn_xid integer,
	fa_submn_xid integer,
	settlement_ccy char(3),
	advised_carrier_id_scheme varchar(64) NOT NULL,
	advised_carrier_id varchar(32) NOT NULL,
	advised_carrier_line_ref varchar(64),
	advised_carrier_line_percent double precision,
	selected_carrier_bureau_code varchar(16),
	selected_carrier_bureau varchar(16),
	selected_carrier_party_sid bigint,
	selected_ocsnd varchar(32),
	contract_carrier_line_xid integer,
	clob_xid integer,
	current_status varchar(100) NOT NULL,
	current_status_datetime timestamp NOT NULL,
	created_date_time timestamp NOT NULL,
	created_user varchar(32) NOT NULL,
	last_updated_date_time timestamp NOT NULL,
	last_updated_user varchar(32) NOT NULL,
	carrier_agreement_role varchar(16),
	original_ccy char(3),
	set_grp_ref varchar(255),
	potential_ocsnds varchar(255),
	broker_code varchar(16),
	partial_mkt_ind varchar(5)
) ;
CREATE INDEX idx_ctl_clm ON pbs_clm_txn_car_lin (claim_xid);
CREATE INDEX idx_ctl_edc ON pbs_clm_txn_car_lin (clob_xid);
CREATE INDEX idx_ctl_rcl ON pbs_clm_txn_car_lin (contract_carrier_line_xid);
CREATE INDEX idx_ctl_svs_cm ON pbs_clm_txn_car_lin (cm_submn_xid);
CREATE INDEX idx_ctl_svs_fa ON pbs_clm_txn_car_lin (fa_submn_xid);
CREATE INDEX idx_ctl_svs_ta ON pbs_clm_txn_car_lin (ta_submn_xid);
ALTER TABLE pbs_clm_txn_car_lin ADD PRIMARY KEY (xid);

CREATE TABLE pbs_clm_txn_car_lin_hst (
	xid integer NOT NULL,
	claim_xid integer NOT NULL,
	current_row_xid integer NOT NULL,
	cm_submn_xid integer,
	history_date_time timestamp,
	history_reason varchar(50),
	ta_submn_xid integer,
	fa_submn_xid integer,
	settlement_ccy char(3),
	advised_carrier_id_scheme varchar(64) NOT NULL,
	advised_carrier_id varchar(32) NOT NULL,
	selected_carrier_bureau varchar(16),
	selected_carrier_bureau_code varchar(32),
	selected_carrier_party_sid bigint,
	advised_carrier_line_ref varchar(64),
	advised_carrier_line_percent double precision,
	contract_carrier_line_xid integer,
	clob_xid integer,
	selected_ocsnd varchar(32),
	current_status varchar(32) NOT NULL,
	current_status_datetime timestamp NOT NULL,
	created_date_time timestamp NOT NULL,
	created_user varchar(32) NOT NULL,
	last_updated_date_time timestamp NOT NULL,
	last_updated_user varchar(32) NOT NULL,
	carrier_agreement_role varchar(16),
	original_ccy char(3),
	set_grp_ref varchar(255),
	potential_ocsnds varchar(255),
	broker_code varchar(16),
	partial_mkt_ind varchar(5)
) ;
ALTER TABLE pbs_clm_txn_car_lin_hst ADD PRIMARY KEY (xid);

CREATE TABLE pbs_clm_txn_hst (
	xid integer NOT NULL,
	claim_xid integer NOT NULL,
	current_status varchar(16) NOT NULL,
	current_status_datetime timestamp NOT NULL,
	created_date_time timestamp NOT NULL,
	created_user varchar(32) NOT NULL,
	last_updated_date_time timestamp NOT NULL,
	last_updated_user varchar(32) NOT NULL,
	effective_date_time timestamp,
	clob_xid integer,
	current_row_xid integer,
	history_date_time timestamp,
	history_reason varchar(50),
	bnd_class varchar(2),
	bnd_sub_class varchar(4),
	bdx_ucr varchar(17),
	bdx_tr varchar(17),
	transaction_ref varchar(32)
) ;

CREATE TABLE pbs_con_car_lin (
	xid integer NOT NULL,
	ins_contract_xid integer,
	carrier_bureau varchar(16),
	carrier_bureau_code varchar(16),
	carrier_line_ref varchar(64) NOT NULL,
	carrier_line_percent double precision NOT NULL,
	clob_xid integer,
	carrier_party_sid bigint,
	current_status varchar(32) NOT NULL,
	current_status_datetime timestamp NOT NULL,
	created_date_time timestamp NOT NULL,
	created_by_user varchar(32) NOT NULL,
	last_updated_date_time timestamp,
	last_updated_user varchar(32),
	consortium_number varchar(32),
	carrier_line_seq_number smallint
) ;
CREATE INDEX idx_ccl_edc ON pbs_con_car_lin (clob_xid);
CREATE INDEX idx_ccl_ict ON pbs_con_car_lin (ins_contract_xid);
CREATE UNIQUE INDEX idx_uq_con_car_lin ON pbs_con_car_lin (ins_contract_xid, carrier_bureau, carrier_bureau_code, carrier_line_ref, carrier_line_percent);
ALTER TABLE pbs_con_car_lin ADD UNIQUE (ins_contract_xid,carrier_bureau,carrier_bureau_code,carrier_line_ref,carrier_line_percent);
ALTER TABLE pbs_con_car_lin ADD PRIMARY KEY (xid);

CREATE TABLE pbs_con_car_lin_hst (
	xid integer NOT NULL,
	current_row_xid integer,
	history_date_time timestamp,
	history_reason varchar(50),
	carrier_line_ref varchar(64) NOT NULL,
	ins_contract_xid integer,
	carrier_bureau varchar(16),
	carrier_bureau_code varchar(16),
	carrier_line_percent double precision NOT NULL,
	clob_xid integer,
	carrier_party_sid bigint,
	current_status varchar(32) NOT NULL,
	current_status_datetime timestamp NOT NULL,
	created_date_time timestamp NOT NULL,
	created_by_user varchar(32) NOT NULL,
	last_updated_date_time timestamp,
	last_updated_user varchar(32),
	consortium_number varchar(32),
	carrier_line_seq_number smallint
) ;
ALTER TABLE pbs_con_car_lin_hst ADD PRIMARY KEY (xid);

CREATE TABLE pbs_cor_act (
	xid integer NOT NULL,
	date_time_taken timestamp NOT NULL,
	by_person_name varchar(64) NOT NULL,
	by_person_xid integer,
	query_xid integer,
	action_type varchar(16) NOT NULL,
	set_value varchar(256),
	narrative varchar(512),
	created_date_time timestamp NOT NULL,
	created_user varchar(32) NOT NULL,
	last_updated_date_time timestamp NOT NULL,
	last_updated_user varchar(32) NOT NULL
) ;
ALTER TABLE pbs_cor_act ADD PRIMARY KEY (xid);

CREATE TABLE pbs_eac_sub_lin (
	xid integer NOT NULL,
	prm_txn_car_lin_xid integer NOT NULL,
	svc_sub_xid integer NOT NULL,
	created_date_time timestamp NOT NULL,
	created_user varchar(32) NOT NULL,
	last_updated_date_time timestamp NOT NULL,
	last_updated_user varchar(32) NOT NULL
) ;
CREATE INDEX idx_esl_ptl ON pbs_eac_sub_lin (prm_txn_car_lin_xid);
CREATE INDEX idx_esl_svs ON pbs_eac_sub_lin (svc_sub_xid);
ALTER TABLE pbs_eac_sub_lin ADD PRIMARY KEY (xid);

CREATE TABLE pbs_ecf_sub_lin (
	xid integer NOT NULL,
	clm_txn_car_lin_xid integer NOT NULL,
	svc_sub_xid integer NOT NULL,
	created_date_time timestamp NOT NULL,
	created_user varchar(32) NOT NULL,
	last_updated_user varchar(32) NOT NULL,
	last_updated_date_time timestamp NOT NULL
) ;
CREATE INDEX idx_csl_ctl ON pbs_ecf_sub_lin (clm_txn_car_lin_xid);
CREATE INDEX idx_csl_ptl ON pbs_ecf_sub_lin (svc_sub_xid);
ALTER TABLE pbs_ecf_sub_lin ADD PRIMARY KEY (xid);

CREATE TABLE pbs_ent_dat_clob (
	xid integer NOT NULL,
	owning_table_alias varchar(8) NOT NULL,
	clob_type varchar(32) NOT NULL,
	clob_date_time timestamp NOT NULL,
	clob_content text NOT NULL
) ;
ALTER TABLE pbs_ent_dat_clob ADD PRIMARY KEY (xid);

CREATE TABLE pbs_ent_dat_clob_hst (
	xid integer NOT NULL,
	owning_table_alias varchar(8) NOT NULL,
	clob_type varchar(32) NOT NULL,
	clob_date_time timestamp NOT NULL,
	clob_content text NOT NULL,
	history_date_time timestamp,
	history_reason varchar(50),
	current_row_xid integer
) ;
ALTER TABLE pbs_ent_dat_clob_hst ADD PRIMARY KEY (xid);

CREATE TABLE pbs_ins_contract (
	xid integer NOT NULL,
	umr varchar(255) NOT NULL,
	broker_code varchar(32),
	broker_party_sid bigint,
	contract_type_code varchar(64) NOT NULL,
	contract_lead_carrier_code varchar(32),
	contract_lead_party_sid bigint,
	requires_refresh char(1),
	clob_xid integer,
	current_status varchar(32) NOT NULL,
	current_status_datetime timestamp NOT NULL,
	created_date_time timestamp NOT NULL,
	created_user varchar(32),
	last_updated_date_time timestamp NOT NULL,
	last_updated_user varchar(32) NOT NULL,
	slip_type_code varchar(1),
	contract_lead_consortia_code varchar(32)
) ;
CREATE INDEX idx_ctt_edc ON pbs_ins_contract (clob_xid);
ALTER TABLE pbs_ins_contract ADD UNIQUE (umr);
ALTER TABLE pbs_ins_contract ADD PRIMARY KEY (xid);

CREATE TABLE pbs_ins_contract_hst (
	xid integer NOT NULL,
	current_row_xid integer NOT NULL,
	umr varchar(255) NOT NULL,
	broker_code varchar(32),
	history_date_time timestamp,
	broker_party_sid bigint,
	history_reason varchar(50),
	contract_type_code varchar(64) NOT NULL,
	contract_lead_carrier_code varchar(32),
	contract_lead_party_sid bigint,
	requires_refresh char(1),
	clob_xid integer,
	current_status varchar(32) NOT NULL,
	current_status_datetime timestamp NOT NULL,
	created_date_time timestamp NOT NULL,
	created_user varchar(32),
	last_updated_date_time timestamp NOT NULL,
	last_updated_user varchar(32) NOT NULL,
	slip_type_code varchar(1),
	contract_lead_consortia_code varchar(32)
) ;
ALTER TABLE pbs_ins_contract_hst ADD PRIMARY KEY (xid);

CREATE TABLE pbs_ogl_sgn (
	xid integer NOT NULL,
	ins_contract_xid integer NOT NULL,
	bureau varchar(32) NOT NULL,
	obsnd varchar(32),
	ocsnd varchar(32),
	entry_type varchar(8),
	bureau_lead_carrier_code varchar(32),
	class_of_business varchar(32) NOT NULL,
	original_currency char(3),
	country varchar(3),
	year_of_account smallint,
	insured varchar(64),
	gross_premium double precision,
	brokerage double precision,
	excess double precision,
	start_date_time timestamp,
	end_date_time timestamp,
	clob_xid integer,
	current_status varchar(32) NOT NULL,
	current_status_datetime timestamp NOT NULL,
	created_date_time timestamp NOT NULL,
	created_user varchar(32) NOT NULL,
	last_updated_date_time timestamp,
	last_updated_user varchar(32),
	bureau_lead_consortia_code varchar(32)
) ;
CREATE INDEX idx_osn_edc_scope ON pbs_ogl_sgn (clob_xid);
CREATE INDEX idx_osn_ict ON pbs_ogl_sgn (ins_contract_xid);
ALTER TABLE pbs_ogl_sgn ADD UNIQUE (ocsnd);
ALTER TABLE pbs_ogl_sgn ADD PRIMARY KEY (xid);

CREATE TABLE pbs_ogl_sgn_hst (
	xid integer NOT NULL,
	current_row_xid integer NOT NULL,
	ins_contract_xid integer NOT NULL,
	bureau varchar(32) NOT NULL,
	history_date_time timestamp,
	history_reason varchar(50),
	obsnd varchar(32),
	ocsnd varchar(32),
	entry_type varchar(8),
	bureau_lead_carrier_code varchar(32),
	class_of_business varchar(32) NOT NULL,
	original_currency char(3),
	country varchar(3),
	year_of_account smallint,
	insured varchar(64),
	gross_premium double precision,
	brokerage double precision,
	excess double precision,
	start_date_time timestamp,
	end_date_time timestamp,
	clob_xid integer,
	current_status varchar(32) NOT NULL,
	current_status_datetime timestamp NOT NULL,
	created_date_time timestamp NOT NULL,
	created_user varchar(32) NOT NULL,
	last_updated_date_time timestamp,
	last_updated_user varchar(32),
	bureau_lead_consortia_code varchar(32)
) ;
ALTER TABLE pbs_ogl_sgn_hst ADD PRIMARY KEY (xid);

CREATE TABLE pbs_org_sgn_mem (
	xid integer NOT NULL,
	orig_signing_xid integer NOT NULL,
	risk_carrier_line_xid integer NOT NULL,
	created_date_time timestamp NOT NULL,
	created_user varchar(32) NOT NULL,
	last_updated_date_time timestamp NOT NULL,
	last_updated_user varchar(32) NOT NULL
) ;
CREATE INDEX idx_osm_osn ON pbs_org_sgn_mem (orig_signing_xid);
CREATE INDEX idx_osm_rcl ON pbs_org_sgn_mem (risk_carrier_line_xid);
CREATE UNIQUE INDEX idx_uq_osm ON pbs_org_sgn_mem (orig_signing_xid, risk_carrier_line_xid);
ALTER TABLE pbs_org_sgn_mem ADD PRIMARY KEY (xid);
ALTER TABLE pbs_org_sgn_mem ADD UNIQUE (orig_signing_xid,risk_carrier_line_xid);

CREATE TABLE pbs_prm_txn_car_lin (
	xid integer NOT NULL,
	contract_xid integer NOT NULL,
	con_carrier_line_xid integer,
	advised_carrier_id_scheme varchar(64) NOT NULL,
	advised_carrier_id varchar(32) NOT NULL,
	advised_carrier_line_ref varchar(50),
	advised_carrier_line_percent double precision,
	selected_carrier_bureau varchar(16),
	selected_carrier_bureau_code varchar(32),
	selected_carrier_party_sid bigint,
	selected_obsnd varchar(32),
	ta_svc_submn_xid integer NOT NULL,
	fa_svc_submn_xid integer,
	current_status varchar(32) NOT NULL,
	current_status_datetime timestamp NOT NULL,
	created_date_time timestamp NOT NULL,
	created_user varchar(32) NOT NULL,
	last_updated_date_time timestamp NOT NULL,
	last_updated_user varchar(32) NOT NULL,
	set_grp_ref varchar(255)
) ;
CREATE INDEX idx_ptl_ccl ON pbs_prm_txn_car_lin (con_carrier_line_xid);
CREATE INDEX idx_ptl_ict ON pbs_prm_txn_car_lin (contract_xid);
CREATE INDEX idx_ptl_svs_fa ON pbs_prm_txn_car_lin (fa_svc_submn_xid);
ALTER TABLE pbs_prm_txn_car_lin ADD UNIQUE (ta_svc_submn_xid);
ALTER TABLE pbs_prm_txn_car_lin ADD PRIMARY KEY (xid);

CREATE TABLE pbs_prm_txn_car_lin_hst (
	xid integer NOT NULL,
	current_row_xid integer NOT NULL,
	history_reason varchar(50),
	history_date_time timestamp,
	contract_xid integer NOT NULL,
	risk_carrier_line_xid integer,
	advised_carrier_id_scheme varchar(64) NOT NULL,
	advised_carrier_id varchar(32) NOT NULL,
	selected_carrier_bureau varchar(16),
	selected_carrier_bureau_code varchar(32),
	selected_carrier_party_sid bigint,
	selected_obsnd varchar(32),
	clob_xid integer,
	ta_svc_submn_xid integer NOT NULL,
	fa_svc_submn_xid integer,
	current_status varchar(32) NOT NULL,
	current_status_datetime timestamp NOT NULL,
	advised_carrier_line_ref varchar(50),
	advised_carrier_line_percent double precision,
	created_date_time timestamp NOT NULL,
	created_user varchar(32) NOT NULL,
	last_updated_date_time timestamp NOT NULL,
	last_updated_user varchar(32) NOT NULL,
	set_grp_ref varchar(255)
) ;
ALTER TABLE pbs_prm_txn_car_lin_hst ADD PRIMARY KEY (xid);

CREATE TABLE pbs_schema_version (
	major_version smallint NOT NULL,
	minor_version smallint NOT NULL,
	increment_version smallint NOT NULL,
	current_version char(1) NOT NULL,
	description varchar(256) NOT NULL,
	sql_file_name varchar(256) NOT NULL,
	created_date_time timestamp NOT NULL,
	created_user varchar(32) NOT NULL
) ;
ALTER TABLE pbs_schema_version ADD PRIMARY KEY (major_version,minor_version,increment_version);

CREATE TABLE pbs_svc_iss (
	xid integer NOT NULL,
	svc_issue_type_code varchar(32) NOT NULL,
	issue_subtype varchar(32),
	svc_sub_xid integer NOT NULL,
	original_ta_uuid varchar(128),
	questioned_value varchar(256),
	candidate_answers varchar(1024),
	date_time_identified timestamp NOT NULL,
	narrative varchar(2048),
	current_status varchar(32),
	current_status_datetime timestamp,
	corrective_action_xid integer,
	created_date_time timestamp NOT NULL,
	created_user varchar(32) NOT NULL,
	last_updated_date_time timestamp NOT NULL,
	last_updated_user varchar(32) NOT NULL
) ;
CREATE INDEX idx_sis_cra ON pbs_svc_iss (corrective_action_xid);
CREATE INDEX idx_sis_svs ON pbs_svc_iss (svc_sub_xid);
ALTER TABLE pbs_svc_iss ADD PRIMARY KEY (xid);

CREATE TABLE pbs_svc_iss_hst (
	xid integer NOT NULL,
	current_row_xid integer NOT NULL,
	svc_issue_type_code varchar(32) NOT NULL,
	history_date_time timestamp,
	issue_subtype varchar(32),
	history_reason varchar(50),
	svc_sub_xid integer NOT NULL,
	original_ta_uuid varchar(128),
	questioned_value varchar(256),
	candidate_answers varchar(1024),
	date_time_identified timestamp NOT NULL,
	narrative varchar(2048),
	current_status varchar(32),
	current_status_datetime timestamp,
	corrective_action_xid integer,
	created_date_time timestamp NOT NULL,
	created_user varchar(32) NOT NULL,
	last_updated_date_time timestamp NOT NULL,
	last_updated_user varchar(32) NOT NULL
) ;
ALTER TABLE pbs_svc_iss_hst ADD PRIMARY KEY (xid);

CREATE TABLE pbs_svc_sub (
	xid integer NOT NULL,
	service varchar(16) NOT NULL,
	message_unique_id varchar(128) NOT NULL,
	message_type varchar(50) NOT NULL,
	sender_id_scheme varchar(32),
	sender_id varchar(32),
	sender_party_sid bigint,
	date_time timestamp NOT NULL,
	content_clob_xid integer,
	validator_output_clob_xid integer,
	current_status varchar(64) NOT NULL,
	current_status_datetime timestamp NOT NULL,
	created_date_time timestamp NOT NULL,
	created_user varchar(32) NOT NULL,
	last_updated_date_time timestamp,
	last_updated_user varchar(32)
) ;
CREATE INDEX idx_svs_edc_content ON pbs_svc_sub (content_clob_xid);
CREATE INDEX idx_svs_edc_valout ON pbs_svc_sub (validator_output_clob_xid);
CREATE INDEX idx_created_date_time ON pbs_svc_sub (created_date_time);
CREATE INDEX idx_uq_svc_sub ON pbs_svc_sub (message_unique_id);
ALTER TABLE pbs_svc_sub ADD PRIMARY KEY (xid);

CREATE TABLE pbs_svc_sub_hst (
	xid integer NOT NULL,
	service varchar(16) NOT NULL,
	message_unique_id varchar(128) NOT NULL,
	message_type varchar(50) NOT NULL,
	sender_id_scheme varchar(32),
	sender_id varchar(32),
	sender_party_sid bigint,
	date_time timestamp NOT NULL,
	content_clob_xid integer,
	validator_output_clob_xid integer,
	current_status varchar(32) NOT NULL,
	current_status_datetime timestamp NOT NULL,
	created_date_time timestamp NOT NULL,
	created_user varchar(32) NOT NULL,
	last_updated_date_time timestamp,
	last_updated_user varchar(32),
	current_row_xid integer NOT NULL,
	history_date_time timestamp,
	history_reason varchar(50)
) ;
ALTER TABLE pbs_svc_sub_hst ADD PRIMARY KEY (xid);

CREATE TABLE pbs_svc_sub_rsp (
	xid integer NOT NULL,
	orig_svc_submission_xid integer NOT NULL,
	message_unique_id varchar(128) NOT NULL,
	message_type varchar(50) NOT NULL,
	date_time_sent timestamp NOT NULL,
	clob_xid integer,
	created_date_time timestamp NOT NULL,
	created_user varchar(32) NOT NULL,
	last_updated_date_time timestamp NOT NULL,
	last_updated_user varchar(32) NOT NULL
) ;
CREATE INDEX idx_ssr_edc ON pbs_svc_sub_rsp (clob_xid);
CREATE INDEX idx_ssr_svs ON pbs_svc_sub_rsp (orig_svc_submission_xid);
ALTER TABLE pbs_svc_sub_rsp ADD UNIQUE (message_unique_id);
ALTER TABLE pbs_svc_sub_rsp ADD PRIMARY KEY (xid);
ALTER TABLE pbs_eac_sub_lin ADD CONSTRAINT fk_esl_ptl FOREIGN KEY (prm_txn_car_lin_xid) REFERENCES pbs_prm_txn_car_lin(xid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE pbs_eac_sub_lin ADD CONSTRAINT fk_esl_svs FOREIGN KEY (svc_sub_xid) REFERENCES pbs_svc_sub(xid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE pbs_svc_iss ADD CONSTRAINT fk_sis_svs FOREIGN KEY (svc_sub_xid) REFERENCES pbs_svc_sub(xid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE pbs_svc_iss ADD CONSTRAINT fk_sis_cra FOREIGN KEY (corrective_action_xid) REFERENCES pbs_cor_act(xid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE pbs_clm_txn_car_lin ADD CONSTRAINT fk_ctl_edc FOREIGN KEY (clob_xid) REFERENCES pbs_ent_dat_clob(xid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE pbs_clm_txn_car_lin ADD CONSTRAINT fk_ctx_clm FOREIGN KEY (claim_xid) REFERENCES pbs_claim(xid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE pbs_clm_txn_car_lin ADD CONSTRAINT fk_ctl_svs_cm FOREIGN KEY (cm_submn_xid) REFERENCES pbs_svc_sub(xid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE pbs_clm_txn_car_lin ADD CONSTRAINT fk_ctl_ccl FOREIGN KEY (contract_carrier_line_xid) REFERENCES pbs_con_car_lin(xid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE pbs_clm_txn_car_lin ADD CONSTRAINT fk_ctl_svs_fa FOREIGN KEY (fa_submn_xid) REFERENCES pbs_svc_sub(xid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE pbs_clm_txn_car_lin ADD CONSTRAINT fk_ctl_svs_ta FOREIGN KEY (ta_submn_xid) REFERENCES pbs_svc_sub(xid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE pbs_con_car_lin ADD CONSTRAINT fk_ccl_edc FOREIGN KEY (clob_xid) REFERENCES pbs_ent_dat_clob(xid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE pbs_con_car_lin ADD CONSTRAINT fk_ccl_ict FOREIGN KEY (ins_contract_xid) REFERENCES pbs_ins_contract(xid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE pbs_svc_sub_rsp ADD CONSTRAINT fk_ssr_svs FOREIGN KEY (orig_svc_submission_xid) REFERENCES pbs_svc_sub(xid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE pbs_svc_sub_rsp ADD CONSTRAINT fk_ssr_edc FOREIGN KEY (clob_xid) REFERENCES pbs_ent_dat_clob(xid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE pbs_prm_txn_car_lin ADD CONSTRAINT fk_ptl_svs_ta FOREIGN KEY (ta_svc_submn_xid) REFERENCES pbs_svc_sub(xid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE pbs_prm_txn_car_lin ADD CONSTRAINT fk_ptl_svs_fa FOREIGN KEY (fa_svc_submn_xid) REFERENCES pbs_svc_sub(xid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE pbs_prm_txn_car_lin ADD CONSTRAINT fk_ptl_ccl FOREIGN KEY (con_carrier_line_xid) REFERENCES pbs_con_car_lin(xid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE pbs_prm_txn_car_lin ADD CONSTRAINT fk_ptl_ict FOREIGN KEY (contract_xid) REFERENCES pbs_ins_contract(xid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE pbs_ins_contract ADD CONSTRAINT fk_ctt_edc FOREIGN KEY (clob_xid) REFERENCES pbs_ent_dat_clob(xid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE pbs_claim ADD CONSTRAINT fk_clm_ict FOREIGN KEY (ins_contract_xid) REFERENCES pbs_ins_contract(xid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE pbs_claim ADD CONSTRAINT fk_clm_edc FOREIGN KEY (clob_xid) REFERENCES pbs_ent_dat_clob(xid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE pbs_svc_sub ADD CONSTRAINT fk_svs_edc_valout FOREIGN KEY (validator_output_clob_xid) REFERENCES pbs_ent_dat_clob(xid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE pbs_svc_sub ADD CONSTRAINT fk_svs_edc_content FOREIGN KEY (content_clob_xid) REFERENCES pbs_ent_dat_clob(xid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE pbs_ecf_sub_lin ADD CONSTRAINT fk_csl_ptl FOREIGN KEY (svc_sub_xid) REFERENCES pbs_svc_sub(xid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE pbs_ecf_sub_lin ADD CONSTRAINT fk_csl_ctl FOREIGN KEY (clm_txn_car_lin_xid) REFERENCES pbs_clm_txn_car_lin(xid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE pbs_ogl_sgn ADD CONSTRAINT fk_osn_ict FOREIGN KEY (ins_contract_xid) REFERENCES pbs_ins_contract(xid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE pbs_ogl_sgn ADD CONSTRAINT fk_osn_edc_scope FOREIGN KEY (clob_xid) REFERENCES pbs_ent_dat_clob(xid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE pbs_org_sgn_mem ADD CONSTRAINT fk_osm_osn FOREIGN KEY (orig_signing_xid) REFERENCES pbs_ogl_sgn(xid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE pbs_org_sgn_mem ADD CONSTRAINT fk_osm_rcl FOREIGN KEY (risk_carrier_line_xid) REFERENCES pbs_con_car_lin(xid) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
-- Generated by Ora2Pg, the Oracle database Schema converter, version 19.1
-- Copyright 2000-2018 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=localhost;sid=orcl;port=1521

SET client_encoding TO 'UTF8';

SET search_path = pbs_datastore;
\set ON_ERROR_STOP ON


SET search_path = pbs_datastore;
BEGIN;
SET search_path = pbs_datastore;

SET search_path = pbs_datastore;

SET search_path = pbs_datastore;

SET search_path = pbs_datastore;

SET search_path = pbs_datastore;

SET search_path = pbs_datastore;

SET search_path = pbs_datastore;

SET search_path = pbs_datastore;

SET search_path = pbs_datastore;

SET search_path = pbs_datastore;

SET search_path = pbs_datastore;

SET search_path = pbs_datastore;

SET search_path = pbs_datastore;

SET search_path = pbs_datastore;

SET search_path = pbs_datastore;

SET search_path = pbs_datastore;

SET search_path = pbs_datastore;

SET search_path = pbs_datastore;

SET search_path = pbs_datastore;

SET search_path = pbs_datastore;

SET search_path = pbs_datastore;

SET search_path = pbs_datastore;

SET search_path = pbs_datastore;

SET search_path = pbs_datastore;

SET search_path = pbs_datastore;

SET search_path = pbs_datastore;

SET search_path = pbs_datastore;

SET search_path = pbs_datastore;

SET search_path = pbs_datastore;


COMMIT;

