-- Generated by Ora2Pg, the Oracle database Schema converter, version 19.1
-- Copyright 2000-2018 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=localhost;sid=orcl;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE SCHEMA pbs_rules;
--ALTER SCHEMA pbs_rules OWNER TO pbs_rules;

SET search_path = pbs_rules;

CREATE TABLE my_stats_table (
	statid varchar(30),
	type char(1),
	version bigint,
	flags bigint,
	c1 varchar(30),
	c2 varchar(30),
	c3 varchar(30),
	c4 varchar(30),
	c5 varchar(30),
	n1 bigint,
	n2 bigint,
	n3 bigint,
	n4 bigint,
	n5 bigint,
	n6 bigint,
	n7 bigint,
	n8 bigint,
	n9 bigint,
	n10 bigint,
	n11 bigint,
	n12 bigint,
	d1 timestamp,
	r1 bytea,
	r2 bytea,
	ch1 varchar(1000),
	cl1 text
) ;
CREATE INDEX idx_my_stats_table ON my_stats_table (statid, type, c5, c1, c2, c3, c4, version);

CREATE TABLE pc_index_flowref (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxcreatesystemid varchar(32),
	pxindexcount bigint,
	pxindexpurpose varchar(32),
	pxinsindexedclass varchar(96),
	pxinsindexedkey varchar(255),
	pxinsname varchar(320),
	pxobjclass varchar(96),
	pxprivilegeclass varchar(64),
	pxprivilegename varchar(256),
	pxupdatedatetime timestamp,
	pxupdateopname varchar(128),
	pxupdateoperator varchar(128),
	pxupdatesystemid varchar(32),
	pycoverclass varchar(96),
	pyflowclass varchar(96),
	pyflowtype varchar(128),
	pylabel varchar(64),
	pzinskey varchar(340) NOT NULL
) ;
ALTER TABLE pc_index_flowref ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr4_base (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxcreatesystemid varchar(32),
	pxhostid varchar(32),
	pxinsid varchar(128),
	pxinsname varchar(128),
	pxobjclass varchar(96),
	pxupdatedatetime timestamp,
	pxupdateopname varchar(128),
	pxupdateoperator varchar(128),
	pxupdatesystemid varchar(32),
	pyapplet varchar(255),
	pyappletharness varchar(64),
	pybaserule varchar(8),
	pycategory varchar(64),
	pycircumstancedateprop varchar(32),
	pycircumstancedate timestamp,
	pycircumstanceprop varchar(64),
	pycircumstancetype varchar(10),
	pycircumstanceval varchar(64),
	pyclassgroup varchar(64),
	pyclassgroupindicator varchar(32),
	pyclassinheritance varchar(8),
	pyclassname varchar(64),
	pyclasstype varchar(64),
	pydatabasename varchar(32),
	pyderivesfrom varchar(64),
	pyformtype varchar(32),
	pyinitialversion varchar(8),
	pylabel varchar(64),
	pymethodstatus varchar(32),
	pypatterninheritance varchar(8),
	pyreportdatabasename varchar(32),
	pyruleavailable varchar(16),
	pyruleends timestamp,
	pyrulename varchar(128),
	pyruleresolution varchar(8),
	pyruleset varchar(64),
	pyrulesetname varchar(64),
	pyrulesetversion varchar(8),
	pzrulesetversionmajor bigint,
	pzrulesetversionminor bigint,
	pzrulesetversionpatch bigint,
	pyrulestarts timestamp,
	pysortdatecircumwithinrsmajor varchar(5),
	pytablename varchar(64),
	pzinskey varchar(255) NOT NULL,
	pzpvstream bytea,
	pzchecksum bigint
) ;
CREATE INDEX idx_base_cat ON pr4_base (pycategory);
CREATE INDEX idx_base_classname ON pr4_base (pyclassname);
CREATE INDEX idx_base_insid ON pr4_base (pxinsid);
CREATE INDEX idx_base_objclass ON pr4_base (pxobjclass);
CREATE INDEX pr4_base_idx1 ON pr4_base (pyclassgroupindicator);
CREATE INDEX pr4_base_idx2 ON pr4_base (pyruleset);
CREATE INDEX pr4_base_idx3 ON pr4_base (pyclassgroup, pyclassgroupindicator, pyclassname);
CREATE INDEX pr4_base_idx4 ON pr4_base (pyclassname, pyclasstype, pxobjclass, pyclassinheritance, pyruleresolution);
CREATE INDEX idx_rule_baseres_1 ON pr4_base (pxinsid, pxobjclass, pyclassname, pyruleavailable);
ALTER TABLE pr4_base ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr4_fieldvalue (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxcreatesystemid varchar(32),
	pxhostid varchar(32),
	pxinsid varchar(128),
	pxinsname varchar(128),
	pxinstancelockedby varchar(128),
	pxinstancelockeddatetime timestamp,
	pxinstancelockedkey varchar(255),
	pxmergesynchronized timestamp,
	pxobjclass varchar(96),
	pxupdatedatetime timestamp,
	pxupdateopname varchar(128),
	pxupdateoperator varchar(128),
	pxupdatesystemid varchar(32),
	pybaserule varchar(8),
	pycircumstancedateprop varchar(32),
	pycircumstancedate timestamp,
	pycircumstanceprop varchar(64),
	pycircumstancetype varchar(10),
	pycircumstanceval varchar(64),
	pyclassname varchar(64),
	pyfieldname varchar(64),
	pyfieldvalue varchar(64),
	pyinterface varchar(64),
	pylabel varchar(64),
	pymethodstatus varchar(32),
	pyruleavailable varchar(16),
	pyruleends timestamp,
	pyrulename varchar(128),
	pyruleset varchar(128),
	pyrulesetversion varchar(8),
	pzrulesetversionmajor bigint,
	pzrulesetversionminor bigint,
	pzrulesetversionpatch bigint,
	pyrulestarts timestamp,
	pysortdatecircumwithinrsmajor varchar(5),
	pzucshortinsid varchar(255),
	pzinskey varchar(255) NOT NULL,
	pzpvstream bytea,
	pylocalizedvalue text,
	pzchecksum bigint
) ;
CREATE INDEX idx_fieldvalue_insid ON pr4_fieldvalue (pxinsid);
CREATE INDEX pr4_fieldvalue_idx1 ON pr4_fieldvalue (pzucshortinsid, pxobjclass, pyruleavailable);
CREATE INDEX idx_rule_fieldvres_1 ON pr4_fieldvalue (pxinsid, pxobjclass, pyclassname, pyruleavailable);
ALTER TABLE pr4_fieldvalue ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr4_rule (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxcreatesystemid varchar(32),
	pxhostid varchar(32),
	pxinsid varchar(128),
	pxinsname varchar(128),
	pxinstancelockedby varchar(128),
	pxinstancelockeddatetime timestamp,
	pxinstancelockedkey varchar(255),
	pxissummary varchar(5),
	pxmergesynchronized timestamp,
	pxobjclass varchar(96),
	pxupdatedatetime timestamp,
	pxupdateopname varchar(128),
	pxupdateoperator varchar(128),
	pxupdatesystemid varchar(32),
	pyaccessibilitylevel bigint,
	pyaccessrole varchar(64),
	pyaccesstoclass varchar(64),
	pyactionname varchar(64),
	pyactivityname varchar(64),
	pyactivitytype varchar(255),
	pyagentname varchar(64),
	pyautohtml varchar(8),
	pybaseclass varchar(64),
	pybaserule varchar(8),
	pyblockname varchar(64),
	pybrowsersupportlevel bigint,
	pycategory varchar(64),
	pychartoutputtype varchar(16),
	pycircumstanceprop varchar(64),
	pycircumstancetype varchar(10),
	pycircumstanceval varchar(64),
	pycircumstancedateprop varchar(32),
	pycircumstancedate timestamp,
	pyclassname varchar(64),
	pycolumninclusion varchar(64),
	pycorrtype varchar(255),
	pycusclass varchar(64),
	pycusmethod varchar(64),
	pycuspackage varchar(64),
	pydecisiontreename varchar(64),
	pydependsonname varchar(32),
	pydependsonversion varchar(32),
	pyeditinputname varchar(32),
	pyeditvalidate varchar(32),
	pyelementname varchar(255),
	pyembeddedlistview varchar(5),
	pyformname varchar(64),
	pyfunctionname varchar(64),
	pyhtmlprompt varchar(64),
	pyisparentincluded varchar(5),
	pyinputmaystart varchar(8),
	pyinterface varchar(64),
	pylabel varchar(64),
	pylibraryname varchar(64),
	pylistclass varchar(64),
	pylistname varchar(64),
	pylocalized varchar(8),
	pymapname varchar(255),
	pymaxlength varchar(16),
	pymessagename varchar(255),
	pymethodname varchar(32),
	pymethodstatus varchar(32),
	pymodelname varchar(64),
	pynamespace varchar(255),
	pyneedsreference varchar(32),
	pyoutputtype varchar(32),
	pyowner varchar(128),
	pypackage varchar(64),
	pypageclass varchar(64),
	pypagename varchar(64),
	pypagecontext varchar(128),
	pypagecontextclass varchar(128),
	pyprivilegename varchar(255),
	pyproductname varchar(32),
	pyproductpatchversion varchar(32),
	pyproductversion varchar(32),
	pyprojectmanagementenabled varchar(5),
	pypromptvalidate varchar(64),
	pypropertymode varchar(32),
	pypropertyname varchar(64),
	pypurpose varchar(64),
	pyqualifiername varchar(64),
	pyqueryname varchar(64),
	pyrwaccess varchar(64),
	pyrecordinsname varchar(128),
	pyrecordtype varchar(64),
	pyresumingprocess varchar(128),
	pyrequesttype varchar(32),
	pyruleavailable varchar(16),
	pyruleends timestamp,
	pyrulename varchar(128),
	pyruleset varchar(128),
	pyrulesetname varchar(64),
	pyrulesettype varchar(64),
	pyrulesetversion varchar(8),
	pyrulesetversionid varchar(8),
	pzrulesetversionmajor bigint,
	pzrulesetversionminor bigint,
	pzrulesetversionpatch bigint,
	pyrulestarts timestamp,
	pyschemaurn varchar(64),
	pyservicelevelname varchar(64),
	pyservicename varchar(255),
	pysettingname varchar(64),
	pyskillname varchar(32),
	pysortdatecircumwithinrsmajor varchar(5),
	pystreamname varchar(64),
	pystringtype varchar(64),
	pysuitename varchar(96),
	pysystemname varchar(32),
	pytableoption varchar(16),
	pytargetproperty varchar(64),
	pyticketname varchar(64),
	pytoplevelcorr varchar(8),
	pyusedas varchar(64),
	pyusegraph varchar(5),
	pyuseredit varchar(16),
	pyvalidatename varchar(64),
	pyversionsecure varchar(16),
	pyworkparty varchar(255),
	pyxmltype varchar(64),
	pymode varchar(255),
	pytargetpropertyclass varchar(64),
	pytargetpropertyname varchar(64),
	pyclasstowrite varchar(96),
	pzinskey varchar(255) NOT NULL,
	pzpvstream bytea,
	pzchecksum bigint
) ;
CREATE INDEX idx_pr4_ruleoc_cn ON pr4_rule (pxobjclass, pyclassname);
CREATE INDEX idx_pr4_ruleruleset ON pr4_rule (pyruleset);
CREATE INDEX pr4_rule_idx1 ON pr4_rule (pyproductname, pyproductversion, pxobjclass);
CREATE INDEX idx_pr4_rule_insname ON pr4_rule (pxinsname);
CREATE INDEX idx_pr4_rule_oc_in ON pr4_rule (pxobjclass, pxinsname);
CREATE INDEX idx_rule_app_hier ON pr4_rule (pyproductname, pyproductversion, pydependsonname, pydependsonversion);
CREATE INDEX idx_rule_insid ON pr4_rule (pxinsid);
CREATE INDEX idx_rule_objclass ON pr4_rule (pxobjclass);
CREATE INDEX idx_rule_pyclassname ON pr4_rule (pyclassname);
CREATE INDEX idx_rule_ruleres ON pr4_rule (pxinsid, pxobjclass);
CREATE INDEX idx_rule_ruleres_1 ON pr4_rule (pxinsid, pxobjclass, pyclassname, pyruleavailable);
ALTER TABLE pr4_rule ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr4_rule_autotest (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxcreatesystemid varchar(32),
	pxhostid varchar(32),
	pxinsid varchar(128),
	pxinsname varchar(128),
	pxinstancelockedby varchar(128),
	pxinstancelockeddatetime timestamp,
	pxinstancelockedkey varchar(255),
	pxmergesynchronized timestamp,
	pxobjclass varchar(96),
	pxupdatedatetime timestamp,
	pxupdateopname varchar(128),
	pxupdateoperator varchar(128),
	pxupdatesystemid varchar(32),
	pybaserule varchar(8),
	pycategory varchar(64),
	pycircumstanceprop varchar(64),
	pycircumstancetype varchar(10),
	pycircumstanceval varchar(64),
	pycircumstancedateprop varchar(32),
	pycircumstancedate timestamp,
	pyclassname varchar(64),
	pyexecutionstatus varchar(32),
	pylabel varchar(64),
	pylastexecutiontime timestamp,
	pylastflowstep varchar(64),
	pymethodname varchar(32),
	pymethodstatus varchar(32),
	pymodelname varchar(64),
	pyparenttestcase varchar(255),
	pyparentruleset varchar(64),
	pyparentrsversion varchar(8),
	pypurpose varchar(64),
	pyrecordinsname varchar(128),
	pyrecordinskey varchar(255),
	pyrecordtype varchar(64),
	pyresumingprocess varchar(128),
	pyruleavailable varchar(16),
	pyruleends timestamp,
	pyrulename varchar(128),
	pyruleset varchar(128),
	pyrulesetname varchar(64),
	pyrulesettype varchar(64),
	pyrulesetversion varchar(8),
	pzrulesetversionmajor bigint,
	pzrulesetversionminor bigint,
	pzrulesetversionpatch bigint,
	pyrulesetversionid varchar(8),
	pyrulestarts timestamp,
	pysortdatecircumwithinrsmajor varchar(5),
	pysuitename varchar(96),
	pyworkparty varchar(255),
	pyxmltype varchar(64),
	pzinskey varchar(255) NOT NULL,
	pyapplicationname varchar(255),
	pyapplicationversion varchar(32),
	pyrecordrulename varchar(128),
	pyrecordclassname varchar(128),
	pzpvstream bytea,
	pzchecksum bigint
) ;
CREATE INDEX idx_autotstres_1 ON pr4_rule_autotest (pxinsid, pxobjclass, pyclassname, pyruleavailable);
ALTER TABLE pr4_rule_autotest ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr4_rule_declarepages (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxcreatesystemid varchar(32),
	pxhostid varchar(32),
	pxinsid varchar(128),
	pxinsname varchar(128),
	pxinstancelockedby varchar(128),
	pxinstancelockeddatetime timestamp,
	pxinstancelockedkey varchar(255),
	pxmergesynchronized timestamp,
	pxobjclass varchar(96),
	pxupdatedatetime timestamp,
	pxupdateopname varchar(128),
	pxupdateoperator varchar(128),
	pxupdatesystemid varchar(32),
	pybaserule varchar(8),
	pycategory varchar(64),
	pycircumstanceprop varchar(64),
	pycircumstancetype varchar(10),
	pycircumstanceval varchar(64),
	pycircumstancedateprop varchar(32),
	pycircumstancedate timestamp,
	pyclassname varchar(64),
	pyinterface varchar(64),
	pylabel varchar(64),
	pymethodstatus varchar(32),
	pypagename varchar(64),
	pyruleavailable varchar(16),
	pyruleends timestamp,
	pyrulename varchar(128),
	pyruleset varchar(128),
	pyrulesetname varchar(64),
	pyrulesetversion varchar(8),
	pzrulesetversionmajor bigint,
	pzrulesetversionminor bigint,
	pzrulesetversionpatch bigint,
	pyrulestarts timestamp,
	pysortdatecircumwithinrsmajor varchar(5),
	pzinskey varchar(255) NOT NULL,
	pysourcecount decimal(18,6),
	pytype varchar(10),
	pyscope varchar(10),
	pystructure varchar(5),
	pzpvstream bytea,
	pzchecksum bigint
) ;
CREATE INDEX idx_pr4_rule_dp_insid ON pr4_rule_declarepages (pxinsid);
CREATE INDEX idx_pr4_rule_dp_insname ON pr4_rule_declarepages (pxinsname);
CREATE INDEX idx_pr4_rule_dp_objclass ON pr4_rule_declarepages (pxobjclass);
CREATE INDEX idx_pr4_rule_dp_oc_cn ON pr4_rule_declarepages (pxobjclass, pyclassname);
CREATE INDEX idx_pr4_rule_dp_oc_in ON pr4_rule_declarepages (pxobjclass, pxinsname);
CREATE INDEX idx_pr4_rule_dp_pyclassname ON pr4_rule_declarepages (pyclassname);
CREATE INDEX idx_pr4_rule_dp_ruleres ON pr4_rule_declarepages (pxinsid, pxobjclass);
CREATE INDEX idx_pr4_rule_dp_ruleres_1 ON pr4_rule_declarepages (pxinsid, pxobjclass, pyclassname, pyruleavailable);
CREATE INDEX idx_pr4_rule_dp_ruleset ON pr4_rule_declarepages (pyruleset);
ALTER TABLE pr4_rule_declarepages ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr4_rule_file (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxcreatesystemid varchar(32),
	pxhostid varchar(32),
	pxinsid varchar(128),
	pxinsname varchar(255),
	pxinstancelockedby varchar(128),
	pxinstancelockeddatetime timestamp,
	pxinstancelockedkey varchar(255),
	pxmergesynchronized timestamp,
	pxobjclass varchar(96),
	pxupdatedatetime timestamp,
	pxupdateopname varchar(128),
	pxupdateoperator varchar(128),
	pxupdatesystemid varchar(32),
	pyapplicationname varchar(255),
	pybaserule varchar(8),
	pybundletype varchar(128),
	pybundlename varchar(255),
	pycircumstancedateprop varchar(32),
	pycircumstancedate timestamp,
	pycircumstanceprop varchar(64),
	pycircumstancetype varchar(10),
	pycircumstanceval varchar(64),
	pyclassname varchar(64),
	pyfilename varchar(255),
	pyfiletype varchar(32),
	pyfilechecksum varchar(128),
	pyinterface varchar(64),
	pylabel varchar(64),
	pymethodstatus varchar(32),
	pyrelativepath varchar(255),
	pyruleavailable varchar(16),
	pyruleends timestamp,
	pyrulename varchar(128),
	pyruleset varchar(64),
	pyrulesetversion varchar(8),
	pzrulesetversionmajor bigint,
	pzrulesetversionminor bigint,
	pzrulesetversionpatch bigint,
	pyrulestarts timestamp,
	pysortdatecircumwithinrsmajor varchar(5),
	pzimplementationkey varchar(255),
	pzucshortinsid varchar(288),
	pzinskey varchar(255) NOT NULL,
	pzpvstream bytea,
	pzchecksum bigint
) ;
CREATE INDEX pr4_rule_file_idx1 ON pr4_rule_file (pzucshortinsid, pxobjclass, pyruleavailable);
CREATE INDEX idx_rf_insidfile ON pr4_rule_file (pxinsid, pxobjclass);
CREATE INDEX idx_rf_insnclass ON pr4_rule_file (pxinsname, pxobjclass);
CREATE INDEX idx_rule_file_insid ON pr4_rule_file (pxinsid);
CREATE INDEX idx_rule_rulefileres_1 ON pr4_rule_file (pxinsid, pxobjclass, pyclassname, pyruleavailable);
ALTER TABLE pr4_rule_file ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr4_rule_file_binary (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxcreatesystemid varchar(32),
	pxhostid varchar(32),
	pxinsid varchar(128),
	pxinsname varchar(255),
	pxinstancelockedby varchar(128),
	pxinstancelockeddatetime timestamp,
	pxinstancelockedkey varchar(255),
	pxmergesynchronized timestamp,
	pxobjclass varchar(96),
	pxupdatedatetime timestamp,
	pxupdateopname varchar(128),
	pxupdateoperator varchar(128),
	pxupdatesystemid varchar(32),
	pyapplicationname varchar(255),
	pybaserule varchar(8),
	pybundletype varchar(128),
	pybundlename varchar(255),
	pycircumstancedateprop varchar(32),
	pycircumstancedate timestamp,
	pycircumstanceprop varchar(64),
	pycircumstancetype varchar(10),
	pycircumstanceval varchar(64),
	pyclassname varchar(64),
	pyfilename varchar(255),
	pyfiletype varchar(32),
	pyfilechecksum varchar(128),
	pyinterface varchar(64),
	pylabel varchar(64),
	pymethodstatus varchar(32),
	pyrelativepath varchar(255),
	pyruleavailable varchar(16),
	pyruleends timestamp,
	pyrulename varchar(128),
	pyruleset varchar(64),
	pyrulesetversion varchar(8),
	pzrulesetversionmajor bigint,
	pzrulesetversionminor bigint,
	pzrulesetversionpatch bigint,
	pyrulestarts timestamp,
	pysortdatecircumwithinrsmajor varchar(5),
	pzimplementationkey varchar(255),
	pzucshortinsid varchar(288),
	pzinskey varchar(255) NOT NULL,
	pzpvstream bytea,
	pzchecksum bigint
) ;
CREATE INDEX pr4_rule_file_binary_idx1 ON pr4_rule_file_binary (pzucshortinsid, pxobjclass, pyruleavailable);
CREATE INDEX pr4_rule_file_binary_idx2 ON pr4_rule_file_binary (pyruleset, pxobjclass);
CREATE INDEX idx_rfb_insnclass ON pr4_rule_file_binary (pxinsname, pxobjclass);
CREATE INDEX idx_rule_rulefilebinaryres_1 ON pr4_rule_file_binary (pxinsid, pxobjclass, pyclassname, pyruleavailable);
ALTER TABLE pr4_rule_file_binary ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr4_rule_flow (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxcreatesystemid varchar(32),
	pxhostid varchar(32),
	pxinsid varchar(128),
	pxinsname varchar(128),
	pxinstancelockedby varchar(128),
	pxinstancelockeddatetime timestamp,
	pxinstancelockedkey varchar(255),
	pxmergesynchronized timestamp,
	pxobjclass varchar(96),
	pxupdatedatetime timestamp,
	pxupdateopname varchar(128),
	pxupdateoperator varchar(128),
	pxupdatesystemid varchar(32),
	pybaserule varchar(8),
	pycancreateworkobject varchar(8),
	pycanstartinteractively varchar(8),
	pycategory varchar(64),
	pycircumstanceprop varchar(64),
	pycircumstancetype varchar(10),
	pycircumstanceval varchar(64),
	pycircumstancedateprop varchar(32),
	pycircumstancedate timestamp,
	pyclassname varchar(64),
	pydescription varchar(255),
	pyflowtype varchar(64),
	pyinterface varchar(64),
	pylabel varchar(64),
	pymethodstatus varchar(32),
	pynamespace varchar(255),
	pyowner varchar(128),
	pypurpose varchar(64),
	pyruleavailable varchar(16),
	pyruleends timestamp,
	pyrulename varchar(128),
	pyruleset varchar(128),
	pyrulesetname varchar(64),
	pyrulesetversion varchar(8),
	pzrulesetversionmajor bigint,
	pzrulesetversionminor bigint,
	pzrulesetversionpatch bigint,
	pyrulesetversionid varchar(8),
	pyrulestarts timestamp,
	pyskipnewharness varchar(8),
	pysortdatecircumwithinrsmajor varchar(5),
	pystartingharness varchar(64),
	pystartingmodel varchar(64),
	pystreamname varchar(64),
	pysystemname varchar(32),
	pyvisiojpegname varchar(259),
	pyvisiorfb varchar(255),
	pystructuretype varchar(16),
	pzinskey varchar(255) NOT NULL,
	pzpvstream bytea,
	pzchecksum bigint
) ;
CREATE INDEX idx_flow_insid ON pr4_rule_flow (pxinsid);
CREATE INDEX idx_flow_objclass ON pr4_rule_flow (pxobjclass);
CREATE INDEX idx_flow_pyclassname ON pr4_rule_flow (pyclassname);
CREATE INDEX idx_flow_resolution ON pr4_rule_flow (pxobjclass, pyrulesetname, pyrulesetversionid);
CREATE INDEX idx_insidfile ON pr4_rule_flow (pxobjclass, pxinsid);
CREATE INDEX idx_rule_flow_insname ON pr4_rule_flow (pxinsname);
CREATE INDEX idx_rule_flow_oc_cn ON pr4_rule_flow (pxobjclass, pyclassname);
CREATE INDEX idx_rule_flow_oc_in ON pr4_rule_flow (pxobjclass, pxinsname);
CREATE INDEX idx_rule_flow_ruleset ON pr4_rule_flow (pyruleset);
CREATE INDEX idx_rule_ruleflowres_1 ON pr4_rule_flow (pxinsid, pxobjclass, pyclassname, pyruleavailable);
ALTER TABLE pr4_rule_flow ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr4_rule_message (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxcreatesystemid varchar(32),
	pxhostid varchar(32),
	pxinsid varchar(128),
	pxinsname varchar(193),
	pxinstancelockedby varchar(128),
	pxinstancelockeddatetime timestamp,
	pxinstancelockedkey varchar(255),
	pxmergesynchronized timestamp,
	pxobjclass varchar(64),
	pxupdatedatetime timestamp,
	pxupdateopname varchar(128),
	pxupdateoperator varchar(128),
	pxupdatesystemid varchar(32),
	pybaserule varchar(8),
	pycategory varchar(64),
	pycircumstanceprop varchar(64),
	pycircumstancetype varchar(10),
	pycircumstanceval varchar(64),
	pycircumstancedateprop varchar(32),
	pycircumstancedate timestamp,
	pyclassname varchar(64),
	pyimpact varchar(64),
	pyinterface varchar(64),
	pylabel varchar(64),
	pymessagename varchar(128),
	pymethodstatus varchar(32),
	pyruleavailable varchar(16),
	pyruleends timestamp,
	pyrulename varchar(128),
	pyruleset varchar(128),
	pyrulesetversion varchar(8),
	pyrulestarts timestamp,
	pyseverity varchar(8),
	pysortdatecircumwithinrsmajor varchar(5),
	pzinskey varchar(315) NOT NULL,
	pzrulesetversionmajor bigint,
	pzrulesetversionminor bigint,
	pzrulesetversionpatch bigint,
	pzpvstream bytea
) ;
CREATE INDEX pr4_rule_message_idx1 ON pr4_rule_message (pymessagename, pycategory, pyseverity);
ALTER TABLE pr4_rule_message ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr4_rule_property (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxcreatesystemid varchar(32),
	pxhostid varchar(32),
	pxinsid varchar(128),
	pxinsname varchar(128),
	pxinstancelockedby varchar(128),
	pxinstancelockeddatetime timestamp,
	pxinstancelockedkey varchar(255),
	pxmergesynchronized timestamp,
	pxobjclass varchar(96),
	pxupdatedatetime timestamp,
	pxupdateopname varchar(128),
	pxupdateoperator varchar(128),
	pxupdatesystemid varchar(32),
	pybaserule varchar(8),
	pycategory varchar(64),
	pycircumstanceprop varchar(64),
	pycircumstancetype varchar(10),
	pycircumstanceval varchar(64),
	pycircumstancedateprop varchar(32),
	pycircumstancedate timestamp,
	pyclassname varchar(64),
	pycolumninclusion varchar(64),
	pyeditvalidate varchar(32),
	pyinterface varchar(64),
	pyisassociation varchar(64),
	pylabel varchar(64),
	pymaxlength varchar(16),
	pymethodstatus varchar(32),
	pynamespace varchar(255),
	pyowner varchar(128),
	pypageclass varchar(64),
	pypropertymode varchar(32),
	pypropertyname varchar(64),
	pypurpose varchar(64),
	pyqualifiername varchar(64),
	pyruleavailable varchar(16),
	pyruleends timestamp,
	pyrulename varchar(128),
	pyruleset varchar(128),
	pyrulesetname varchar(64),
	pyrulesetversion varchar(8),
	pzrulesetversionmajor bigint,
	pzrulesetversionminor bigint,
	pzrulesetversionpatch bigint,
	pyrulesetversionid varchar(8),
	pyrulestarts timestamp,
	pysortdatecircumwithinrsmajor varchar(5),
	pystreamname varchar(64),
	pystringtype varchar(64),
	pysystemname varchar(32),
	pytableoption varchar(16),
	pyvisiorfb varchar(255),
	pydataretrievaltype varchar(64),
	pyadvancedproptype varchar(64),
	pydataobjectclass varchar(96),
	pyisreference varchar(5),
	pygatewayclass varchar(96),
	pydataobject varchar(128),
	pyjavaobjectclass varchar(128),
	pzinskey varchar(255) NOT NULL,
	pzpvstream bytea,
	pzchecksum bigint
) ;
CREATE INDEX idx_property_insid ON pr4_rule_property (pxinsid);
CREATE INDEX idx_property_insname ON pr4_rule_property (pxinsname);
CREATE INDEX idx_property_objclass ON pr4_rule_property (pxobjclass);
CREATE INDEX idx_property_oc_cn ON pr4_rule_property (pxobjclass, pyclassname);
CREATE INDEX idx_property_oc_in ON pr4_rule_property (pxobjclass, pxinsname);
CREATE INDEX idx_property_ruleset ON pr4_rule_property (pyruleset);
CREATE INDEX idx_prop_pyclassname ON pr4_rule_property (pyclassname);
CREATE INDEX idx_prop_resolution ON pr4_rule_property (pxobjclass, pyrulesetname, pyrulesetversionid);
CREATE INDEX idx_rule_propres_1 ON pr4_rule_property (pxinsid, pxobjclass, pyclassname, pyruleavailable);
CREATE INDEX idx_rule_prop_insid ON pr4_rule_property (pxobjclass, pxinsid);
ALTER TABLE pr4_rule_property ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr4_rule_requirement (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxcreatesystemid varchar(32),
	pxhostid varchar(32),
	pxinsid varchar(128),
	pxinsname varchar(128),
	pxinstancelockedby varchar(128),
	pxinstancelockeddatetime timestamp,
	pxinstancelockedkey varchar(255),
	pxinstancelockedruleset varchar(128),
	pxmergesynchronized timestamp,
	pxobjclass varchar(96),
	pxupdatedatetime timestamp,
	pxupdateopname varchar(128),
	pxupdateoperator varchar(128),
	pxupdatesystemid varchar(32),
	pybaserule varchar(8),
	pycategory varchar(64),
	pycircumstanceprop varchar(64),
	pycircumstancetype varchar(10),
	pycircumstanceval varchar(64),
	pycircumstancedateprop varchar(32),
	pycircumstancedate timestamp,
	pyclassname varchar(64),
	pyinterface varchar(64),
	pylabel varchar(64),
	pymethodstatus varchar(32),
	pyproductname varchar(32),
	pypurpose varchar(64),
	pyruleavailable varchar(16),
	pyruleends timestamp,
	pyrulename varchar(128),
	pyruleset varchar(128),
	pyrulesetversion varchar(8),
	pzrulesetversionmajor bigint,
	pzrulesetversionminor bigint,
	pzrulesetversionpatch bigint,
	pyrulestarts timestamp,
	pysettingname varchar(64),
	pysortdatecircumwithinrsmajor varchar(5),
	pyusedas varchar(64),
	pyimportance varchar(64),
	pyexternalid varchar(64),
	pzinskey varchar(255) NOT NULL,
	pzpvstream bytea,
	pyattachmentscount bigint,
	pzchecksum bigint,
	pyrelease varchar(128),
	pyiteration varchar(128)
) ;
CREATE INDEX idx_pr4_rule_requirementoc_cn ON pr4_rule_requirement (pxobjclass, pyclassname);
CREATE INDEX idx_pr4_rule_requirement_insname ON pr4_rule_requirement (pxinsname);
CREATE INDEX idx_pr4_rule_requirement_oc_in ON pr4_rule_requirement (pxobjclass, pxinsname);
CREATE INDEX idx_pr4_rule_req_ruleset ON pr4_rule_requirement (pyruleset);
CREATE INDEX idx_rule_requirement_insid ON pr4_rule_requirement (pxinsid);
CREATE INDEX idx_rule_requirement_objclass ON pr4_rule_requirement (pxobjclass);
CREATE INDEX idx_rule_requirement_pyclassname ON pr4_rule_requirement (pyclassname);
CREATE INDEX idx_rule_requirement_ruleres ON pr4_rule_requirement (pxinsid, pxobjclass);
CREATE INDEX idx_rule_requirement_ruleres_1 ON pr4_rule_requirement (pxinsid, pxobjclass, pyclassname, pyruleavailable);
ALTER TABLE pr4_rule_requirement ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr4_rule_ruleset (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxcreatesystemid varchar(32),
	pxinsid varchar(128),
	pxinsname varchar(128),
	pxobjclass varchar(96),
	pxupdatedatetime timestamp,
	pxupdateopname varchar(128),
	pxupdateoperator varchar(128),
	pxupdatesystemid varchar(32),
	pxhostid varchar(32),
	pylabel varchar(64),
	pzinskey varchar(255) NOT NULL,
	pzpvstream bytea,
	pyruleset varchar(128),
	pyrulename varchar(128),
	pyrulesetname varchar(64),
	pyrulesetversionid varchar(8),
	pyrulesettype varchar(64),
	pybranchid varchar(16),
	pybranchorigin varchar(64),
	pybranchoriginversion varchar(8),
	pyversionsecure varchar(5),
	pzchecksum bigint
) ;
CREATE INDEX pr4_rule_ruleset_idx1 ON pr4_rule_ruleset (pyrulesetname, pyrulesettype);
CREATE INDEX pr4_rule_ruleset_idx2 ON pr4_rule_ruleset (pyruleset);
CREATE INDEX idx_rule_resolution_rrs ON pr4_rule_ruleset (pxobjclass, pyrulesetname, pyrulesetversionid);
ALTER TABLE pr4_rule_ruleset ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr4_rule_shortcut (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxcreatesystemid varchar(32),
	pxhostid varchar(32),
	pxinsid varchar(128),
	pxinsname varchar(128),
	pxinstancelockedby varchar(128),
	pxinstancelockeddatetime timestamp,
	pxinstancelockedkey varchar(255),
	pxmergesynchronized timestamp,
	pxobjclass varchar(96),
	pxupdatedatetime timestamp,
	pxupdateopname varchar(128),
	pxupdateoperator varchar(128),
	pxupdatesystemid varchar(32),
	pybaserule varchar(8),
	pycategory varchar(64),
	pycircumstanceprop varchar(64),
	pycircumstancetype varchar(10),
	pycircumstanceval varchar(64),
	pycircumstancedateprop varchar(32),
	pycircumstancedate timestamp,
	pyclassname varchar(64),
	pylabel varchar(64),
	pylastflowstep varchar(64),
	pymethodname varchar(32),
	pymethodstatus varchar(32),
	pymodelname varchar(64),
	pyparenttestcase varchar(255),
	pypurpose varchar(64),
	pyrecordinsname varchar(128),
	pyrecordinskey varchar(255),
	pyreporttype varchar(128),
	pylastexecutiontime timestamp,
	pyresumingprocess varchar(128),
	pyruleavailable varchar(16),
	pyruleends timestamp,
	pyrulename varchar(128),
	pyruleset varchar(128),
	pyrulesetname varchar(64),
	pyrulesettype varchar(64),
	pyrulesetversion varchar(8),
	pzrulesetversionmajor bigint,
	pzrulesetversionminor bigint,
	pzrulesetversionpatch bigint,
	pyrulesetversionid varchar(8),
	pyrulestarts timestamp,
	pysortdatecircumwithinrsmajor varchar(5),
	pysuitename varchar(96),
	pyvisiblewhen varchar(128),
	pyworkparty varchar(255),
	pyxmltype varchar(64),
	pycategoryname varchar(128),
	pyownertype varchar(10),
	pyowner varchar(128),
	pydescription varchar(256),
	pyshortcutname varchar(128),
	pyshortcutdescription varchar(256),
	pyshortcutoperator varchar(128),
	pyshortcuttitle varchar(128),
	pyruletype varchar(32),
	pyruleclassname varchar(64),
	pyruleobjclass varchar(96),
	pyruleinsname varchar(128),
	pzinskey varchar(255) NOT NULL,
	pzpvstream bytea,
	pzchecksum bigint
) ;
CREATE INDEX pr4_rule_shorctcut_idx1 ON pr4_rule_shortcut (pxinsname, pxobjclass);
CREATE INDEX idx_rule_shortcres_1 ON pr4_rule_shortcut (pxinsid, pxobjclass, pyclassname, pyruleavailable);
CREATE INDEX shortcut_owner_idx ON pr4_rule_shortcut (pyownertype, pyowner);
ALTER TABLE pr4_rule_shortcut ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr4_rule_sysgen (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxcreatesystemid varchar(32),
	pxinsid varchar(128),
	pxinsname varchar(230),
	pxinstancelockedby varchar(128),
	pxobjclass varchar(96),
	pxupdatedatetime timestamp,
	pxupdateopname varchar(128),
	pxupdateoperator varchar(128),
	pxupdatesystemid varchar(32),
	pybaserule varchar(8),
	pycircumstancedateprop varchar(32),
	pycircumstancedate timestamp,
	pycircumstanceprop varchar(64),
	pycircumstancetype varchar(10),
	pycircumstanceval varchar(64),
	pyclassname varchar(64),
	pylabel varchar(64),
	pyruleavailable varchar(16),
	pyruleends timestamp,
	pyrulename varchar(128),
	pyruleset varchar(128),
	pyrulesetname varchar(64),
	pyrulesetversion varchar(8),
	pzrulesetversionmajor bigint,
	pzrulesetversionminor bigint,
	pzrulesetversionpatch bigint,
	pyrulesetversionid varchar(8),
	pyrulestarts timestamp,
	pysortdatecircumwithinrsmajor varchar(5),
	pzinskey varchar(255) NOT NULL,
	pzpvstream bytea,
	pzchecksum bigint
) ;
CREATE INDEX idx_rule_sysgres_1 ON pr4_rule_sysgen (pxinsid, pxobjclass, pyclassname, pyruleavailable);
CREATE INDEX idx_sysgen_insid ON pr4_rule_sysgen (pxinsid);
CREATE INDEX idx_sysgen_insname ON pr4_rule_sysgen (pxinsname);
CREATE INDEX idx_sysgen_objclass ON pr4_rule_sysgen (pxobjclass);
CREATE INDEX idx_sysgen_oc_cn ON pr4_rule_sysgen (pxobjclass, pyclassname);
CREATE INDEX idx_sysgen_oc_in ON pr4_rule_sysgen (pxobjclass, pxinsname);
CREATE INDEX idx_sysgen_pyclassname ON pr4_rule_sysgen (pyclassname);
CREATE INDEX idx_sysgen_resolution ON pr4_rule_sysgen (pxobjclass, pyrulesetname, pyrulesetversionid);
CREATE INDEX idx_sysgen_ruleset ON pr4_rule_sysgen (pyruleset);
ALTER TABLE pr4_rule_sysgen ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr4_rule_usecase (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxcreatesystemid varchar(32),
	pxhostid varchar(32),
	pxinsid varchar(128),
	pxinsname varchar(128),
	pxinstancelockedby varchar(128),
	pxinstancelockeddatetime timestamp,
	pxinstancelockedkey varchar(255),
	pxinstancelockedruleset varchar(128),
	pxmergesynchronized timestamp,
	pxobjclass varchar(96),
	pxupdatedatetime timestamp,
	pxupdateopname varchar(128),
	pxupdateoperator varchar(128),
	pxupdatesystemid varchar(32),
	pybaserule varchar(8),
	pycategory varchar(64),
	pylabel varchar(64),
	pyowner varchar(128),
	pymethodstatus varchar(32),
	pyproductname varchar(32),
	pypurpose varchar(64),
	pyruleavailable varchar(16),
	pyruleends timestamp,
	pyrulename varchar(128),
	pyruleset varchar(128),
	pyrulesetversion varchar(8),
	pzrulesetversionmajor bigint,
	pzrulesetversionminor bigint,
	pzrulesetversionpatch bigint,
	pyrulestarts timestamp,
	pysortdatecircumwithinrsmajor varchar(5),
	pyspecformat varchar(64),
	pyusedas varchar(64),
	pycircumstanceprop varchar(64),
	pycircumstancetype varchar(10),
	pycircumstanceval varchar(64),
	pycircumstancedateprop varchar(32),
	pycircumstancedate timestamp,
	pyclassname varchar(64),
	pyinterface varchar(64),
	pyestimateddevelopmenteffort varchar(128),
	pzinskey varchar(255) NOT NULL,
	pyoldpurpose varchar(64),
	pyoldproductname varchar(32),
	pyoldowner varchar(128),
	pyprotocol varchar(128),
	pynumberofinterchanges bigint,
	pycommentscount bigint,
	pyattachmentscount bigint,
	pyisdatasourceexists varchar(5),
	pzpvstream bytea,
	pzchecksum bigint,
	pydsmsubtype varchar(64),
	pydsmissue varchar(64),
	pydsmgroup varchar(64),
	pydsmtype varchar(64),
	pydsmchannel varchar(64),
	pydsmassociatedproposition varchar(64),
	pydsmpredictoravailability varchar(64),
	pydsmmodelsnumber bigint,
	pydsmsegmentsnumber bigint,
	pyrelease varchar(128),
	pyiteration varchar(128)
) ;
CREATE INDEX idx_pr4_ruleucruleset ON pr4_rule_usecase (pyruleset);
CREATE INDEX idx_pr4_rule_usecaseoc_cn ON pr4_rule_usecase (pxobjclass, pyclassname);
CREATE INDEX idx_pr4_rule_usecase_insname ON pr4_rule_usecase (pxinsname);
CREATE INDEX idx_pr4_rule_usecase_oc_in ON pr4_rule_usecase (pxobjclass, pxinsname);
CREATE INDEX idx_rule_usecase_insid ON pr4_rule_usecase (pxinsid);
CREATE INDEX idx_rule_usecase_objclass ON pr4_rule_usecase (pxobjclass);
CREATE INDEX idx_rule_usecase_pyclassname ON pr4_rule_usecase (pyclassname);
CREATE INDEX idx_rule_usecase_ruleres ON pr4_rule_usecase (pxinsid, pxobjclass);
CREATE INDEX idx_rule_usecase_ruleres_1 ON pr4_rule_usecase (pxinsid, pxobjclass, pyclassname, pyruleavailable);
ALTER TABLE pr4_rule_usecase ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr4_rule_vw (
	pxcreatedatetime timestamp,
	pxobjclass varchar(96),
	pxinsid varchar(128),
	pxinsname varchar(193),
	pxinstancelockedby varchar(255),
	pxinstancelockedkey varchar(255),
	pxmergesynchronized timestamp,
	pxupdatedatetime timestamp,
	pxupdateoperator varchar(128),
	pxupdateopname varchar(128),
	pyclass varchar(96),
	pyclassname varchar(64),
	pycircumstancedate timestamp,
	pycircumstancedateprop varchar(32),
	pycircumstanceprop varchar(64),
	pycircumstancetype varchar(10),
	pycircumstanceval varchar(64),
	pyinterface varchar(64),
	pylabel varchar(64),
	pymethodstatus varchar(32),
	pyruleavailable varchar(16),
	pyrulename varchar(128),
	pyruleset varchar(128),
	pyrulesetversion varchar(8),
	pzrulesetversionmajor bigint,
	pzrulesetversionminor bigint,
	pzrulesetversionpatch bigint,
	pzrulesetversionminorpatch varchar(5),
	pyrulestarts timestamp,
	pyruleends timestamp,
	pzinskey varchar(315) NOT NULL,
	pzclasstype smallint
) ;
CREATE INDEX pr4_rule_vw_idx1 ON pr4_rule_vw (pxobjclass, pxupdatedatetime);
CREATE INDEX pr4_rule_vw_idx2 ON pr4_rule_vw (pxinsname, pxobjclass, pyrulesetversion, pyruleset);
CREATE INDEX pr4_rule_vw_idx3 ON pr4_rule_vw (pxinsid, pyclass, pyruleset, pzrulesetversionmajor, pzrulesetversionminor, pzrulesetversionpatch, pyclassname);
CREATE INDEX pr4_rule_vw_idx4 ON pr4_rule_vw (pyruleset, pzrulesetversionmajor, pzrulesetversionminor, pzrulesetversionpatch, pyclass);
CREATE INDEX pr4_rule_vw_idx5 ON pr4_rule_vw (pyruleset, pzclasstype, pzrulesetversionmajor, pzrulesetversionminorpatch);
CREATE INDEX pr4_rule_vw_idx6 ON pr4_rule_vw (pyruleset, pzclasstype, pyruleavailable);
CREATE INDEX idx_pr4_view_op ON pr4_rule_vw (pxupdateoperator);
CREATE INDEX idx_pr4_vwoc_cn ON pr4_rule_vw (pyclass, pyclassname);
CREATE INDEX idx_pr4_vwruleset ON pr4_rule_vw (pyruleset);
CREATE INDEX idx_pr4_vw_insname ON pr4_rule_vw (pxinsname);
CREATE INDEX idx_pr4_vw_oc_in ON pr4_rule_vw (pyclass, pxinsname);
CREATE INDEX idx_vw_insid ON pr4_rule_vw (pxinsid);
CREATE INDEX idx_vw_objclass ON pr4_rule_vw (pyclass);
CREATE INDEX idx_vw_pyclassname ON pr4_rule_vw (pyclassname);
CREATE INDEX idx_vw_resolution ON pr4_rule_vw (pyclass, pyrulesetversion);
CREATE INDEX idx_vw_updatedatetime ON pr4_rule_vw (pxupdatedatetime);
ALTER TABLE pr4_rule_vw ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_app_branch_idx (
	pxcommitdatetime timestamp,
	pxobjclass varchar(32) NOT NULL,
	pxindexcount bigint,
	pxindexpurpose varchar(32),
	pxinsindexedclass varchar(96),
	pxinsindexedkey varchar(255),
	pxinsname varchar(256) NOT NULL,
	pzappname varchar(128) NOT NULL,
	pzappversion varchar(32) NOT NULL,
	pybranchid varchar(16),
	pzinskey varchar(256) NOT NULL
) ;
CREATE INDEX idx_app_branch_idx_key ON pr_app_branch_idx (pzappname, pzappversion);
CREATE INDEX idx_branch_id_idx_key ON pr_app_branch_idx (pybranchid);
ALTER TABLE pr_app_branch_idx ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_assembledclasses (
	pzjar varchar(128) NOT NULL,
	pzpackage varchar(256) NOT NULL,
	pzclass varchar(256) NOT NULL,
	pzlastmodified timestamp,
	pzsha1 varchar(28) NOT NULL,
	pzbinarycontent bytea,
	pzcacheconfigid varchar(64) NOT NULL,
	pzgenerationdate bigint NOT NULL
) ;
CREATE INDEX idx_pr_assembledclasses_package ON pr_assembledclasses (pzpackage, pzcacheconfigid);
ALTER TABLE pr_assembledclasses ADD PRIMARY KEY (pzcacheconfigid,pzgenerationdate,pzjar,pzpackage,pzclass);

CREATE TABLE pr_changelog (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreateoperator varchar(128),
	pxcreatesystemid varchar(32),
	pxinsname varchar(255),
	pxobjclass varchar(96),
	pyoperation varchar(64),
	pyversion varchar(64),
	pycatalogname varchar(64),
	pydatabasename varchar(32),
	pyschemaname varchar(64),
	pytablename varchar(96),
	pyclonedfrom varchar(96),
	pzinskey varchar(255) NOT NULL,
	pzpvstream bytea,
	pycolumnname varchar(64),
	pychangesource varchar(32),
	pyindexname varchar(64),
	pylatest varchar(16),
	pyisnewtable varchar(5)
) ;
ALTER TABLE pr_changelog ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_data_admin_product (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxcreatesystemid varchar(32),
	pxinsname varchar(385),
	pxobjclass varchar(96),
	pxproductname varchar(32),
	pxproductpatchversion varchar(32),
	pxproductversion varchar(32),
	pxupdatedatetime timestamp,
	pxupdateopname varchar(128),
	pxupdateoperator varchar(128),
	pxupdatesystemid varchar(32),
	pylabel varchar(64),
	pyname varchar(32),
	pyowner varchar(128),
	pyrulesetname varchar(64),
	pysystemname varchar(32),
	pysetting varchar(4000),
	pzinstalltype varchar(32),
	pzinskey varchar(412) NOT NULL,
	pzpvstream bytea
) ;
ALTER TABLE pr_data_admin_product ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_data_map_entries (
	pxcommitdatetime timestamp,
	pxobjclass varchar(32),
	pxinsname varchar(256),
	pycategory varchar(64),
	pydescription varchar(256),
	pyid varchar(64),
	pylabel varchar(128),
	pynodecaption varchar(128),
	pyreference varchar(256),
	pyusage varchar(64),
	pzinskey varchar(256) NOT NULL
) ;
CREATE INDEX pr_data_map_entries_idx ON pr_data_map_entries (pyid, pyusage, pycategory);
ALTER TABLE pr_data_map_entries ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_data_products (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreatesystemid varchar(32),
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxinsname varchar(128),
	pxobjclass varchar(96),
	pxupdatedatetime timestamp,
	pxupdateopname varchar(128),
	pxupdateoperator varchar(128),
	pxupdatesystemid varchar(32),
	pylabel varchar(128),
	pyproductname varchar(255),
	pyproductversion varchar(32),
	pyproductid varchar(32),
	pyparentproductid varchar(255),
	pystatus varchar(16),
	pyuniqueid varchar(16),
	pzinskey varchar(255) NOT NULL,
	pyrulesetname varchar(64)
) ;
ALTER TABLE pr_data_products ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_data_restore (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreatesystemid varchar(32),
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxinsname varchar(128),
	pxobjclass varchar(96),
	pxupdatedatetime timestamp,
	pxupdateopname varchar(128),
	pxupdateoperator varchar(128),
	pxupdatesystemid varchar(32),
	pylabel varchar(64),
	pyparentreference varchar(255),
	pyinstallorder bigint,
	pzinskey varchar(255) NOT NULL,
	pyrulesetname varchar(64),
	pzpvstream bytea
) ;
ALTER TABLE pr_data_restore ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_data_rule_appmetadata (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxcreatesystemid varchar(32),
	pxinsname varchar(128),
	pxobjclass varchar(96),
	pyappname varchar(64),
	pyappversion varchar(32),
	pymetadatakey varchar(255),
	pymetadatatype varchar(64),
	pyrulesetname varchar(64),
	pzinskey varchar(255) NOT NULL
) ;
ALTER TABLE pr_data_rule_appmetadata ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_data_scanner (
	pxcommitdatetime timestamp,
	pxcriticalmissingcount bigint,
	pxuncomittedhotfixcount bigint,
	pxinstalledhotfixcount bigint,
	pxprpcversion varchar(128),
	pxcreatedatetime timestamp,
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxcreatesystemid varchar(32),
	pxinsname varchar(128),
	pxobjclass varchar(96),
	pxupdatedatetime timestamp,
	pxupdateopname varchar(128),
	pxupdateoperator varchar(128),
	pxupdatesystemid varchar(32),
	pylabel varchar(64),
	pyrulesetname varchar(64),
	pzinskey varchar(255) NOT NULL,
	pzpvstream bytea
) ;
CREATE INDEX pr_data_scanner_idx1 ON pr_data_scanner (pxcreatedatetime);
ALTER TABLE pr_data_scanner ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_engineclasses (
	pzjar varchar(128) NOT NULL,
	pzpackage varchar(256) NOT NULL,
	pzclass varchar(256) NOT NULL,
	pzlastmodified timestamp,
	pzsha1 varchar(28) NOT NULL,
	pzmoduleversion varchar(64) NOT NULL,
	pzcodeset varchar(64) NOT NULL,
	pzcodesetversion varchar(8) NOT NULL,
	pzpatchdate timestamp NOT NULL,
	pzstate bigint NOT NULL,
	pzbinarycontent bytea
) ;
CREATE INDEX idx_pr_engclass_code ON pr_engineclasses (pzcodeset, pzcodesetversion, pzpatchdate);
CREATE INDEX idx_pr_engclass_pkg ON pr_engineclasses (pzpackage, pzclass);
CREATE INDEX idx_pr_engclass_querykey ON pr_engineclasses (pzjar, pzpackage, pzclass);
ALTER TABLE pr_engineclasses ADD PRIMARY KEY (pzjar,pzpackage,pzclass,pzpatchdate);

CREATE TABLE pr_index_circumstance_def (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreateoperator varchar(128),
	pxcreateopname varchar(128),
	pxcreatesystemid varchar(32),
	pxindexcount bigint,
	pxindexpurpose varchar(32),
	pxindexedclass varchar(96),
	pxinsindexedclass varchar(96),
	pxinsindexedkey varchar(255),
	pxinsname varchar(385),
	pxobjclass varchar(96),
	pxupdatedatetime timestamp,
	pxupdateoperator varchar(128),
	pxupdateopname varchar(128),
	pxupdatesystemid varchar(32),
	pycountry varchar(64),
	pycity varchar(64),
	pydefinitionname varchar(128),
	pytemplatename varchar(128),
	pylabel varchar(64),
	pyregion varchar(64),
	pystate varchar(64),
	pychannel varchar(32),
	pylevel varchar(64),
	pycompany varchar(64),
	pyorg varchar(64),
	pydept varchar(64),
	pypostalcode varchar(32),
	pzinskey varchar(512) NOT NULL,
	carriername varchar(32),
	bureau varchar(32),
	correctionindicator varchar(32),
	generatemanualfdo varchar(5),
	proceedwithpartialmarket varchar(5),
	processname varchar(32),
	isconsortiummessage varchar(5)
) ;
CREATE INDEX idx_keypurposeidx_cirdef ON pr_index_circumstance_def (pxinsindexedkey, pxindexpurpose);
ALTER TABLE pr_index_circumstance_def ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_index_css (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxcreatesystemid varchar(32),
	pxindexcount bigint,
	pxindexpurpose varchar(32),
	pxinsindexedclass varchar(96),
	pxinsindexedkey varchar(255),
	pxinsname varchar(255),
	pxobjclass varchar(96),
	pxprivilegeclass varchar(64),
	pxprivilegename varchar(256),
	pxupdatedatetime timestamp,
	pxupdateopname varchar(128),
	pxupdateoperator varchar(128),
	pxupdatesystemid varchar(32),
	pylabel varchar(64),
	pxselectorname varchar(64),
	pxrulesetname varchar(128),
	pyrulesetversion varchar(8),
	pzrulesetversionmajor bigint,
	pzrulesetversionminor bigint,
	pzrulesetversionpatch bigint,
	pzinskey varchar(255) NOT NULL
) ;
CREATE INDEX css_index1 ON pr_index_css (pxselectorname);
CREATE INDEX idx_css_indexed_key ON pr_index_css (pxinsindexedkey);
CREATE INDEX idx_keypurposeidx_css ON pr_index_css (pxinsindexedkey, pxindexpurpose);
ALTER TABLE pr_index_css ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_index_customfields (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxcreatesystemid varchar(32),
	pxindexcount bigint,
	pxindexpurpose varchar(32),
	pxinsindexedclass varchar(96),
	pxinsindexedkey varchar(255),
	pxinsname varchar(255),
	pxobjclass varchar(96),
	pxreferencingclassname varchar(96),
	pxreferencingdescription varchar(64),
	pxreferencinginsname varchar(128),
	pxreferencingobjclass varchar(96),
	pxreferencingruleinskey varchar(255),
	pxreferencingrulesetname varchar(128),
	pxreferencingrulesetversion varchar(8),
	pxupdatedatetime timestamp,
	pxupdateopname varchar(128),
	pxupdateoperator varchar(128),
	pxupdatesystemid varchar(32),
	pycategory varchar(64),
	pycfieldname varchar(64),
	pycfieldtype varchar(32),
	pycfieldvalue varchar(255),
	pycfilekey varchar(255),
	pycfilerelativepath varchar(96),
	pychannel varchar(30),
	pygallerytype varchar(64),
	pykeys varchar(255),
	pylabel varchar(64),
	pylob varchar(64),
	pyplanid varchar(64),
	pyregion varchar(20),
	pystate varchar(3),
	pzinskey varchar(255) NOT NULL,
	pzpvstream bytea
) ;
CREATE INDEX idx_customfields ON pr_index_customfields (pxindexpurpose, pxinsindexedkey);
ALTER TABLE pr_index_customfields ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_index_datasources (
	pxcommitdatetime timestamp,
	pxindexcount bigint,
	pxindexpurpose varchar(32),
	pxinsindexedclass varchar(96),
	pxinsindexedkey varchar(255),
	pxinsname varchar(128),
	pxobjclass varchar(96),
	pysourcewhen varchar(64),
	pystructure varchar(4),
	pyclassname varchar(96),
	pydeclarepagesdatasource varchar(32),
	pydtname varchar(64),
	pyconnectorname varchar(255),
	pyconnectortype varchar(96),
	pyconnectorclassname varchar(96),
	pyrestmethod varchar(4),
	pyreportdefinitionclass varchar(96),
	pyloadreportdefinition varchar(64),
	pyloadactivity varchar(64),
	pylookupclassname varchar(96),
	pyissimulated varchar(5),
	pylabel varchar(64),
	pyconnectorinsname varchar(128),
	pydatasourceidentifier varchar(1024),
	pzinskey varchar(256) NOT NULL
) ;
CREATE INDEX idx_pr_datasource_type ON pr_index_datasources (pxinsindexedkey);
ALTER TABLE pr_index_datasources ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_index_privilege (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxcreatesystemid varchar(32),
	pxindexcount bigint,
	pxindexpurpose varchar(32),
	pxinsindexedclass varchar(96),
	pxinsindexedkey varchar(255),
	pxinsname varchar(128),
	pxobjclass varchar(96),
	pxprivilegeclass varchar(64),
	pxprivilegename varchar(256),
	pxupdatedatetime timestamp,
	pxupdateopname varchar(128),
	pxupdateoperator varchar(128),
	pxupdatesystemid varchar(32),
	pylabel varchar(64),
	pzinskey varchar(255) NOT NULL
) ;
CREATE INDEX idx_insindexedkeyprivilege ON pr_index_privilege (pxinsindexedkey);
CREATE INDEX idx_keypurposeidxprivilege ON pr_index_privilege (pxinsindexedkey, pxindexpurpose);
ALTER TABLE pr_index_privilege ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_index_reference (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxcreatesystemid varchar(32),
	pxindexcount bigint,
	pxindexpurpose varchar(32),
	pxinsindexedclass varchar(96),
	pxinsindexedkey varchar(255),
	pxinsname varchar(255),
	pxjavaclass varchar(96),
	pxjavamethodname varchar(64),
	pxobjclass varchar(96),
	pxpagename varchar(64),
	pxreferencingdescription varchar(64),
	pxreferencinginsname varchar(193),
	pxreferencingrulesetname varchar(64),
	pxreferencingrulesetversion varchar(8),
	pxruleclassname varchar(64),
	pxrulefamilyname varchar(128),
	pxruleobjclass varchar(96),
	pxupdatedatetime timestamp,
	pxupdateopname varchar(128),
	pxupdateoperator varchar(128),
	pxupdatesystemid varchar(32),
	pylabel varchar(64),
	pyrulename varchar(128),
	pzinskey varchar(255) NOT NULL
) ;
CREATE INDEX idx_index_ref ON pr_index_reference (pxindexpurpose, pxinsindexedkey);
CREATE INDEX idx_index_refport ON pr_index_reference (pxreferencingrulesetname, pxruleclassname, pxreferencinginsname);
CREATE INDEX idx_pr_index_reference_index1 ON pr_index_reference (pxinsindexedclass, pxruleobjclass, pxreferencingrulesetname);
CREATE INDEX idx_ref_index ON pr_index_reference (pxinsindexedkey, pxruleobjclass);
CREATE INDEX idx_ref_objclass ON pr_index_reference (pxruleobjclass);
CREATE INDEX idx_ref_rules ON pr_index_reference (pxrulefamilyname, pxruleobjclass, pxobjclass, pxindexpurpose);
ALTER TABLE pr_index_reference ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_index_rule_agents (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxcreatesystemid varchar(32),
	pxinsname varchar(192),
	pxobjclass varchar(96),
	pxupdatedatetime timestamp,
	pxupdateopname varchar(128),
	pxupdateoperator varchar(128),
	pxupdatesystemid varchar(32),
	pxindexcount bigint,
	pxindexpurpose varchar(32),
	pxinsindexedclass varchar(96),
	pxinsindexedkey varchar(255),
	pxprivilegeclass varchar(64),
	pxprivilegename varchar(255),
	pylabel varchar(64),
	pytriggerintervalall bigint,
	pyagentname varchar(255),
	pyagentcategory varchar(32),
	pydailyoptions varchar(32),
	pydequeueactivity varchar(32),
	pyenableagent varchar(5),
	pyenableall varchar(5),
	pyendcount bigint,
	pyenddate varchar(8),
	pyusetimezone varchar(8),
	pyerroractivity varchar(32),
	pyexecutiontype varchar(32),
	pylasttriggertime timestamp,
	pymaxrecords bigint,
	pymonthlyoptions varchar(32),
	pymustusequeuemanager varchar(5),
	pyparallelinscount bigint,
	pyqueueclass varchar(128),
	pyqueuemode varchar(32),
	pyrecurringfrequency varchar(32),
	pystarthourdisplayed varchar(32),
	pytriggerintervalagent bigint,
	pyuseautomaticqueuemanagement varchar(5),
	pyuseenddate varchar(5),
	pyyearlyoptions varchar(32),
	pyruleset varchar(128),
	pyaccessgroup varchar(32),
	pybypassactivityauthentication varchar(5),
	pyruleinskey varchar(255) NOT NULL,
	pzinskey varchar(255) NOT NULL,
	pydailyinterval bigint,
	pydayofmonth bigint,
	pydayofmonthinterval bigint,
	pydayselection varchar(64),
	pyeveryweekday varchar(5),
	pyisdayofmonth varchar(5),
	pyismonthandday varchar(5),
	pymonthlydayselection varchar(32),
	pymonthlyinterval bigint,
	pymonthlyweekselection varchar(32),
	pyselecteddays varchar(5),
	pytype varchar(32),
	pyweeklyinterval bigint,
	pyyearlyday bigint,
	pyyearlydayselection varchar(32),
	pyyearlyinterval bigint,
	pyyearlymonth varchar(32),
	pyyearlymonthselection varchar(32),
	pyyearlyweekselection varchar(32)
) ;
CREATE INDEX pr_index_rule_agents_idx1 ON pr_index_rule_agents (pxinsindexedclass);
ALTER TABLE pr_index_rule_agents ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_index_warnings (
	pxcommitdatetime timestamp,
	pxindexcount bigint,
	pxindexpurpose varchar(32),
	pxinsindexedclass varchar(96),
	pxinsindexedkey varchar(255),
	pxinsname varchar(255),
	pxobjclass varchar(96),
	pxreferencingcircdate timestamp,
	pxreferencingcircdateprop varchar(64),
	pxreferencingcircprop varchar(64),
	pxreferencingcircval varchar(64),
	pxreferencingclassname varchar(96),
	pxreferencingdescription varchar(64),
	pxreferencinginsname varchar(255),
	pxreferencingobjclass varchar(96),
	pxreferencingruleends timestamp,
	pxreferencingruleinskey varchar(255),
	pxreferencingrulename varchar(128),
	pxreferencingrulesetname varchar(64),
	pxreferencingrulesetversion varchar(8),
	pxreferencingrulestarts timestamp,
	pxwarningdetails varchar(512),
	pxwarningname varchar(64),
	pxwarningseverity bigint,
	pxwarningtype varchar(64),
	pxiswarningjustified varchar(5),
	pywarningjustifiedmessage varchar(512),
	pxwarningcreatedtime timestamp,
	pzinskey varchar(255) NOT NULL,
	pxwarningcreateoperator varchar(128),
	pxwarningjustifyoperator varchar(128),
	pxwarningrulesettype varchar(32)
) ;
CREATE INDEX idx_idxwarnings ON pr_index_warnings (pxinsindexedkey);
CREATE INDEX idx_keypurposeidx_warn ON pr_index_warnings (pxinsindexedkey, pxindexpurpose);
CREATE INDEX pr_index_warnings_idx1 ON pr_index_warnings (pxreferencingruleinskey, pxobjclass, pxwarningcreatedtime, pxwarningcreateoperator, pxwarningseverity);
ALTER TABLE pr_index_warnings ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_link_usecase (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxcreatesystemid varchar(32),
	pxinsname varchar(128),
	pxlinkedclassfrom varchar(255),
	pxlinkedclassto varchar(255),
	pxlinkedreffrom varchar(255),
	pxlinkedrefto varchar(255),
	pxobjclass varchar(96),
	pxupdatedatetime timestamp,
	pxupdateoperator varchar(128),
	pxupdateopname varchar(128),
	pxupdatesystemid varchar(32),
	pykeyhashcode varchar(255),
	pylabel varchar(64),
	pylinkedclassname varchar(64),
	pyflowkey varchar(255),
	pyflowtype varchar(64),
	pytaskid varchar(64),
	pytaskname varchar(128),
	pyapplicationname varchar(32),
	pyworktypename varchar(64),
	pyusecasename varchar(64),
	pyimplementationtype varchar(32),
	pyinfloworder bigint,
	pzinskey varchar(255) NOT NULL,
	pzpvstream bytea
) ;
CREATE INDEX idx_pr_link_usecase_faobj ON pr_link_usecase (pyflowkey, pxobjclass);
CREATE INDEX idx_pr_link_usecase_linkref ON pr_link_usecase (pxlinkedrefto);
CREATE INDEX idx_pr_link_usecase_linkreffrom ON pr_link_usecase (pxlinkedreffrom);
ALTER TABLE pr_link_usecase ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_reference_page (
	pxcommitdatetime timestamp,
	pxindexcount bigint,
	pxindexpurpose varchar(32),
	pxinsindexedclass varchar(96),
	pxinsindexedkey varchar(255),
	pxinsname varchar(255),
	pxobjclass varchar(96),
	pzinskey varchar(256) NOT NULL,
	pxpagename varchar(64),
	pxpageclass varchar(96),
	pxreferencingdescription varchar(64),
	pxreferencinginsname varchar(128),
	pxreferencingrulesetname varchar(64),
	pxreferencingrulesetversion varchar(8),
	pxruleclassname varchar(64),
	pylabel varchar(64)
) ;
CREATE INDEX pr_reference_page_idx1 ON pr_reference_page (pxindexpurpose, pxinsindexedkey);
CREATE INDEX pr_reference_page_idx2 ON pr_reference_page (pxinsindexedkey, pxpageclass);
CREATE INDEX pr_reference_page_idx3 ON pr_reference_page (pxreferencingrulesetname, pxruleclassname, pxreferencinginsname);
CREATE INDEX idx_pr_ref_page_pageclass ON pr_reference_page (pxpageclass);
ALTER TABLE pr_reference_page ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_sysgen_static_content (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxcreatesystemid varchar(32),
	pxinsname varchar(349),
	pxobjclass varchar(96),
	pyapplicationname varchar(256),
	pybasefilename varchar(255),
	pyfilename varchar(255),
	pyfiletype varchar(32),
	pzcacheconfigid varchar(64),
	pzpackage varchar(256),
	pzclass varchar(256),
	pzinskey varchar(370) NOT NULL,
	pzpvstream bytea
) ;
CREATE INDEX pr_sysgen_static_content_idx2 ON pr_sysgen_static_content (pyapplicationname, pyfilename, pyfiletype, pzcacheconfigid);
CREATE INDEX pr_sysgen_static_content_idx3 ON pr_sysgen_static_content (pyapplicationname, pybasefilename, pyfiletype, pzcacheconfigid);
CREATE INDEX pr_sysgen_static_content_idx4 ON pr_sysgen_static_content (pzclass, pzpackage, pyfiletype, pxcreatedatetime);
ALTER TABLE pr_sysgen_static_content ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_sys_appcache_dep (
	pxcommitdatetime timestamp,
	pzrulesetname varchar(128),
	pzrulesetversionmajor bigint,
	pzrulesetversionminor bigint,
	pzrulesetversionpatch bigint,
	pzdepruleinskey varchar(200),
	pzinskey varchar(576) NOT NULL,
	pzimplementationkey varchar(255),
	pzdependencykey varchar(255),
	pzappliestoclassname varchar(64),
	pzruletype varchar(64),
	pzrulename varchar(255),
	pzexplicitinlineclass varchar(5),
	pxobjclass varchar(96),
	pzcacheconfigid varchar(18),
	pxcreatedatetime timestamp,
	pxcreatesystemid varchar(32),
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pzdepruleinsid varchar(128),
	pxinsname varchar(512),
	pzassemblytimeclass varchar(64),
	pzexcludefromaa varchar(5),
	pzpackage varchar(256),
	pzclass varchar(256),
	pzmodelindex bigint,
	pzclasshash varchar(32),
	pzexplicitexcludecombined bigint
) ;
CREATE INDEX pr_sys_appcache_dep_idx1 ON pr_sys_appcache_dep (pzclasshash, pzimplementationkey, pzcacheconfigid, pzexplicitexcludecombined, pzappliestoclassname, pzdepruleinsid, pzruletype, pzmodelindex, pzassemblytimeclass);
CREATE INDEX pr_sys_appcache_dep_idx2 ON pr_sys_appcache_dep (pzrulename, pzruletype, pzcacheconfigid, pzexplicitexcludecombined, pzimplementationkey, pzappliestoclassname, pzassemblytimeclass, pzrulesetname, pzrulesetversionmajor, pzrulesetversionminor, pzrulesetversionpatch);
CREATE INDEX pr_sys_appcache_dep_idx4 ON pr_sys_appcache_dep (pzimplementationkey, pzcacheconfigid, pzrulename, pzruletype);
ALTER TABLE pr_sys_appcache_dep ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_sys_appcache_entry (
	pxcommitdatetime timestamp,
	pzrulename varchar(128),
	pzruletype varchar(64),
	pzqualifiedrulename varchar(255),
	pzprimarypageclassname varchar(64),
	pzcontextpathhash varchar(32),
	pzappname varchar(255),
	pzappversion varchar(255),
	pzapphash varchar(128),
	pzimplementationkey varchar(192),
	pzentrysource varchar(32),
	pxobjclass varchar(96),
	pzaspect varchar(32),
	pzentrykey varchar(255),
	pzinskey varchar(320) NOT NULL,
	pxinsname varchar(400),
	pzcacheconfigid varchar(64),
	pzexpirationtime timestamp,
	pzcreationelapsetime decimal(18,6),
	pxcreatedatetime timestamp,
	pxcreatesystemid varchar(32),
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pzsafetoinfer varchar(5),
	pzpackage varchar(256),
	pzclass varchar(256),
	pzassembletimeleafclassname varchar(64)
) ;
CREATE INDEX idx_appentry_apphash ON pr_sys_appcache_entry (pzapphash);
CREATE INDEX idx_appentry_impl ON pr_sys_appcache_entry (pzimplementationkey);
CREATE INDEX idx_appentry_rule ON pr_sys_appcache_entry (pzrulename, pzruletype);
CREATE INDEX pr_sys_appcache_entry_idx1 ON pr_sys_appcache_entry (pzimplementationkey, pzapphash, pzprimarypageclassname, pzrulename, pzruletype, pzinskey, pzassembletimeleafclassname);
CREATE INDEX pr_sys_appcache_entry_idx2 ON pr_sys_appcache_entry (pzclass, pzpackage);
ALTER TABLE pr_sys_appcache_entry ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_sys_appcache_shortcut (
	pxcommitdatetime timestamp,
	pzrulename varchar(128),
	pzruletype varchar(64),
	pzqualifiedrulename varchar(255),
	pzprimarypageclassname varchar(64),
	pzappname varchar(255),
	pzappversion varchar(255),
	pzapphash varchar(128),
	pzimplementationkey varchar(192),
	pzentrysource varchar(32),
	pxobjclass varchar(96),
	pzaspect varchar(32),
	pzentrykey varchar(255),
	pzinskey varchar(320) NOT NULL,
	pxinsname varchar(350),
	pzcacheconfigid varchar(64),
	pzexpirationtime timestamp,
	pzcreationelapsetime decimal(18,6),
	pxcreatedatetime timestamp,
	pxcreatesystemid varchar(32),
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pzpackage varchar(256),
	pzclass varchar(256)
) ;
CREATE INDEX idx_appshortcut_entrykey ON pr_sys_appcache_shortcut (pzentrykey, pzcacheconfigid);
CREATE INDEX pr_sys_appcache_shortcut_idx1 ON pr_sys_appcache_shortcut (pzimplementationkey, pzapphash, pzprimarypageclassname, pzrulename, pzruletype, pzinskey);
CREATE INDEX pr_sys_appcache_shortcut_idx2 ON pr_sys_appcache_shortcut (pzapphash);
ALTER TABLE pr_sys_appcache_shortcut ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_sys_app_hierarchy_flat (
	pxcommitdatetime timestamp,
	pztopapphash varchar(255) NOT NULL,
	pzappname varchar(128) NOT NULL,
	pzappversion varchar(32) NOT NULL,
	pzapphash varchar(255) NOT NULL,
	pzbuiltonappname varchar(128),
	pzbuiltonappversion varchar(32),
	pzbuiltonapphash varchar(255),
	pzappheight bigint,
	pztopapptype bigint,
	pxobjclass varchar(96),
	pxinsname varchar(340),
	pzinskey varchar(375) NOT NULL,
	pxcreatedatetime timestamp,
	pxupdatedatetime timestamp
) ;
CREATE INDEX idx_apphierarchyflat_report ON pr_sys_app_hierarchy_flat (pzappname, pzappversion, pzappheight, pzapphash);
CREATE INDEX pr_sys_app_hierarchy_flat_idx1 ON pr_sys_app_hierarchy_flat (pztopapphash, pzapphash, pzappheight);
CREATE INDEX pr_sys_app_hierarchy_flat_idx2 ON pr_sys_app_hierarchy_flat (pzapphash, pztopapphash, pztopapptype, pzbuiltonapphash);
CREATE INDEX pr_sys_app_hierarchy_flat_idx3 ON pr_sys_app_hierarchy_flat (pztopapptype, pzapphash, pztopapphash, pzbuiltonapphash);
ALTER TABLE pr_sys_app_hierarchy_flat ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_sys_app_ruleset_index (
	pxcommitdatetime timestamp,
	pzappname varchar(128) NOT NULL,
	pzappversion varchar(32) NOT NULL,
	pzrulesetindex bigint NOT NULL,
	pzrulesetname varchar(128) NOT NULL,
	pzrulesetversionmajor bigint NOT NULL,
	pzrulesetversionminor bigint NOT NULL,
	pzrulesetversionpatch bigint NOT NULL,
	pzrulesetversionminorpatch varchar(5),
	pzrulesettype char(1) NOT NULL,
	pzinskey varchar(256) NOT NULL,
	pxobjclass varchar(32) NOT NULL,
	pxcreatedatetime timestamp,
	pxcreatesystemid varchar(32),
	pxcreateoperator varchar(128),
	pxcreateopname varchar(128),
	pxinsname varchar(256) NOT NULL,
	pzapphash varchar(255)
) ;
CREATE INDEX idx_app_ruleset_app_rule_version ON pr_sys_app_ruleset_index (pzapphash, pzrulesetname, pzrulesetversionmajor, pzrulesetversionminor, pzrulesetversionpatch, pzrulesetindex);
CREATE INDEX idx_app_ruleset_rule_version ON pr_sys_app_ruleset_index (pzrulesetname, pzapphash, pzrulesetversionmajor, pzrulesetversionminor, pzrulesetversionpatch, pzrulesetindex);
CREATE INDEX idx_pr_sari_appverrs ON pr_sys_app_ruleset_index (pzappname, pzappversion, pzrulesetname, pzrulesetversionmajor, pzrulesetversionminor, pzrulesetversionpatch);
CREATE INDEX pr_sys_app_ruleset_index_idx4 ON pr_sys_app_ruleset_index (pzapphash, pzrulesetname, pzrulesetversionmajor, pzrulesetversionminorpatch);
ALTER TABLE pr_sys_app_ruleset_index ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_sys_cache_dep (
	pxcommitdatetime timestamp,
	pzimplementationkey varchar(255),
	pzdependencykey varchar(255),
	pzentrytype varchar(255),
	pxcreatedatetime timestamp,
	pxcreatesystemid varchar(32),
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxobjclass varchar(96),
	pxinsname varchar(512),
	pzinskey varchar(576) NOT NULL,
	pzcacheconfigid varchar(64),
	pzappliestoclassname varchar(255),
	pzruletype varchar(255),
	pzrulename varchar(255),
	pzexplicitinlineclass varchar(5),
	pzdepruleinsid varchar(128),
	pzpackage varchar(256),
	pzclass varchar(256)
) ;
CREATE INDEX idx_cache_dep_dep ON pr_sys_cache_dep (pzdependencykey);
CREATE INDEX idx_cache_dep_impl ON pr_sys_cache_dep (pzimplementationkey);
CREATE INDEX idx_dep_ruleinsid ON pr_sys_cache_dep (pzdepruleinsid, pzruletype);
ALTER TABLE pr_sys_cache_dep ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_sys_cache_entry (
	pxcommitdatetime timestamp,
	pzimplementationkey varchar(255),
	pzrulename varchar(255),
	pzrulesetlisthash varchar(255),
	pzruletype varchar(255),
	pzentrykey varchar(255),
	pzentrytype varchar(255),
	pzseenby varchar(64),
	pzcreationelapsetime decimal(18,6),
	pxcreatedatetime timestamp,
	pzexpirationtime timestamp,
	pxcreatesystemid varchar(32),
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxobjclass varchar(96),
	pxinsname varchar(255),
	pzinskey varchar(255) NOT NULL,
	pzpvstream bytea,
	pzprimarypageclassname varchar(255),
	pzcacheconfigid varchar(64),
	pzsharedrulesetlisthash varchar(255),
	pzentrysource varchar(32),
	pzpackage varchar(256),
	pzclass varchar(256)
) ;
CREATE INDEX idx_cache_entry_hash ON pr_sys_cache_entry (pzrulesetlisthash);
CREATE INDEX idx_cache_entry_impl ON pr_sys_cache_entry (pzimplementationkey);
CREATE INDEX idx_cache_entry_rule ON pr_sys_cache_entry (pzruletype, pzcacheconfigid, pzprimarypageclassname);
CREATE INDEX pr_sys_cache_entry_idx2 ON pr_sys_cache_entry (pzclass, pzpackage);
ALTER TABLE pr_sys_cache_entry ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_sys_cache_impl (
	pxcommitdatetime timestamp,
	pzimplementationkey varchar(255),
	pzimplementationtype varchar(255),
	pzrulename varchar(255),
	pzruletype varchar(255),
	pzseenby varchar(64),
	pxcreatedatetime timestamp,
	pxcreatesystemid varchar(32),
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxobjclass varchar(96),
	pxinsname varchar(255),
	pzinskey varchar(255) NOT NULL,
	pzpvstream bytea,
	pzappliestoclassname varchar(255),
	pzcacheconfigid varchar(64),
	pzpackage varchar(256),
	pzclass varchar(256)
) ;
CREATE INDEX idx_cache_impl_impl ON pr_sys_cache_impl (pzimplementationkey);
CREATE INDEX idx_cache_impl_rulename ON pr_sys_cache_impl (pzrulename);
ALTER TABLE pr_sys_cache_impl ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_sys_class_ancestors (
	pxcommitdatetime timestamp,
	pxleafclassname varchar(96) NOT NULL,
	pxucleafclassname varchar(96) NOT NULL,
	pxclassname varchar(96) NOT NULL,
	pxucclassname varchar(96),
	pxhashkey varchar(32) NOT NULL,
	pxheight bigint NOT NULL,
	pxcreatedatetime timestamp,
	pxcreateopname varchar(128),
	pxcreateoperator varchar(128),
	pxcreatesystemid varchar(32),
	pxinsname varchar(256),
	pxobjclass varchar(96),
	pxupdatedatetime timestamp,
	pxupdateopname varchar(128),
	pxupdateoperator varchar(128),
	pxupdatesystemid varchar(32),
	pylabel varchar(64),
	pzinskey varchar(512) NOT NULL
) ;
CREATE INDEX idx_pr_sys_class_ancestors_cc ON pr_sys_class_ancestors (pxucleafclassname, pxhashkey);
CREATE INDEX pr_sys_class_ancestors_idx1 ON pr_sys_class_ancestors (pxclassname, pxleafclassname, pxheight);
CREATE INDEX idx_pr_sys_class_ancest_rr ON pr_sys_class_ancestors (pxleafclassname, pxclassname, pxheight);
CREATE INDEX idx_pr_sys_class_ancest_rr2 ON pr_sys_class_ancestors (pxleafclassname, pxucclassname, pxheight);
ALTER TABLE pr_sys_class_ancestors ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_sys_context (
	pxcommitdatetime timestamp,
	pxcontextexpires timestamp,
	pxcreatedatetime timestamp,
	pxinsname varchar(128),
	pxlabel varchar(128),
	pxobjclass varchar(96),
	pxoperator varchar(128),
	pxrequestorid varchar(64),
	pxupdatedatetime timestamp,
	pzinskey varchar(255) NOT NULL,
	pzpvstream bytea
) ;
ALTER TABLE pr_sys_context ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_sys_decchg (
	pxcommitdatetime timestamp,
	pxchangeclass varchar(96) NOT NULL,
	pxchangeobjclass varchar(96),
	pxchangeproperty varchar(64),
	pxchangepurpose varchar(96),
	pxchangetype varchar(8) NOT NULL,
	pxdefindex bigint NOT NULL,
	pxinsname varchar(256) NOT NULL,
	pxobjclass varchar(96) NOT NULL,
	pxruleappliesto varchar(96) NOT NULL,
	pxrulekey varchar(256) NOT NULL,
	pxruleobjclass varchar(96) NOT NULL,
	pxruleset varchar(64) NOT NULL,
	pxrulesetversion varchar(8) NOT NULL,
	pzinskey varchar(512) NOT NULL
) ;
CREATE INDEX idx_sdc_class ON pr_sys_decchg (pxchangeclass);
CREATE INDEX idx_sdc_key ON pr_sys_decchg (pxrulekey);
CREATE INDEX idx_sdc_prop ON pr_sys_decchg (pxchangeproperty);
ALTER TABLE pr_sys_decchg ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_sys_ruleset_index (
	pxcommitdatetime timestamp,
	pxcreatedatetime timestamp,
	pxcreateopname varchar(128),
	pxcreatesystemid varchar(32),
	pxinsname varchar(128),
	pzrulesetindex bigint,
	pxobjclass varchar(96),
	pzrulesetname varchar(128),
	pyrulesetversion varchar(8),
	pzrulesetversionmajor bigint,
	pzrulesetversionminor bigint,
	pzrulesetversionpatch bigint,
	pzrulesetversionminorpatch varchar(5),
	pzrulesetlisthash varchar(255),
	pzinskey varchar(255) NOT NULL
) ;
CREATE INDEX pr_sys_ruleset_index_idx1 ON pr_sys_ruleset_index (pzrulesetlisthash, pzrulesetname, pzrulesetversionmajor, pzrulesetversionminorpatch, pzrulesetindex);
CREATE INDEX idx_rulesetname ON pr_sys_ruleset_index (pzrulesetname, pzrulesetversionmajor, pzrulesetversionminor, pzrulesetversionpatch, pzrulesetlisthash);
CREATE INDEX idx_rule_res_rule_join ON pr_sys_ruleset_index (pzrulesetlisthash, pzrulesetname, pzrulesetversionmajor, pzrulesetversionminor, pzrulesetversionpatch);
ALTER TABLE pr_sys_ruleset_index ADD PRIMARY KEY (pzinskey);

CREATE TABLE pr_sys_rule_impl (
	pxcommitdatetime timestamp,
	pzinskey varchar(576) NOT NULL,
	pzpackage varchar(256),
	pzclass varchar(256),
	pzpreload varchar(5),
	pzruleinskey varchar(512),
	pzaspect varchar(16),
	pxinsname varchar(528),
	pxobjclass varchar(96),
	pxupdatedatetime timestamp,
	pzchecksum bigint
) ;
CREATE INDEX pr_sys_rule_idx1 ON pr_sys_rule_impl (pzruleinskey);
CREATE INDEX pr_sys_rule_impl_idx1 ON pr_sys_rule_impl (pzclass, pzpackage);
ALTER TABLE pr_sys_rule_impl ADD PRIMARY KEY (pzinskey);
-- Generated by Ora2Pg, the Oracle database Schema converter, version 19.1
-- Copyright 2000-2018 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=localhost;sid=orcl;port=1521

SET client_encoding TO 'UTF8';

SET search_path = pbs_rules;
\set ON_ERROR_STOP ON


SET search_path = pbs_rules;
BEGIN;
SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;

SET search_path = pbs_rules;


COMMIT;

